//HintName: MyApp.NetConfig.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591

namespace MyApp;

partial record NetConfig
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("Net")]</c>.
    /// </summary>
    public const string SectionName = "Net";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    public NetConfig(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_HostsSection = section.GetSection("Hosts");
        var _cb_HostsList = new global::System.Collections.Generic.List<string>();
        foreach (var _cb_HostsChild in _cb_HostsSection.GetChildren())
        {
            if (_cb_HostsChild.Value is not null) _cb_HostsList.Add(_cb_HostsChild.Value);
        }
        if (_cb_HostsList.Count > 0)
        {
            this.Hosts = _cb_HostsList.ToArray();
        }
        var _cb_PortsSection = section.GetSection("Ports");
        var _cb_PortsList = new global::System.Collections.Generic.List<int>();
        foreach (var _cb_PortsChild in _cb_PortsSection.GetChildren())
        {
            if (_cb_PortsChild.Value is not null && int.TryParse(_cb_PortsChild.Value, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_ep)) _cb_PortsList.Add(_cb_ep);
        }
        if (_cb_PortsList.Count > 0)
        {
            this.Ports = _cb_PortsList;
        }
        var _cb_HeadersSection = section.GetSection("Headers");
        var _cb_HeadersDict = new global::System.Collections.Generic.Dictionary<string, string>();
        foreach (var _cb_HeadersChild in _cb_HeadersSection.GetChildren())
        {
            if (_cb_HeadersChild.Value is not null) _cb_HeadersDict[_cb_HeadersChild.Key] = _cb_HeadersChild.Value;
        }
        if (_cb_HeadersDict.Count > 0)
        {
            this.Headers = _cb_HeadersDict;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="NetConfig"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<NetConfig>
    {
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, NetConfig options)
            => Validate(name, SectionName, options);
        
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, string path, NetConfig options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("NetConfig instance was null.");
            }
            
            var failures = new global::System.Collections.Generic.List<string>();
            
            if (options.Hosts is null)
            {
                failures.Add("[" + path + ":Hosts] is required but was null.");
            }
            if (options.Ports is null)
            {
                failures.Add("[" + path + ":Ports] is required but was null.");
            }
            if (options.Headers is null)
            {
                failures.Add("[" + path + ":Headers] is required but was null.");
            }
            
            options.ValidateCustom(failures);
            options.ValidateCustom(failures, path);
            
            return failures.Count > 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures)
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Success;
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
    
    /// <summary>
    /// Path-aware overload of the custom validation hook. Implement this
    /// partial method instead of (or alongside) the single-argument form
    /// when you want to include the full runtime configuration path in
    /// your failure messages — useful for types that can be used as
    /// nested or element configs, where the path differs per usage site.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    /// <param name="path">Full configuration path to this options instance, e.g. <c>"Api:Endpoints:1"</c>.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures, string path);
}

/// <summary>
/// Dependency-injection helpers for <see cref="NetConfig"/>.
/// </summary>
public static class NetConfigServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="NetConfig"/> to the <c>"Net"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddNetConfig(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(NetConfig.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<NetConfig>, NetConfig.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<NetConfig>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<NetConfig>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<NetConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<NetConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<NetConfig>>(sp),
                    _ => new NetConfig(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<NetConfig>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<NetConfig>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
