//HintName: ConfigBoundNET.SensitiveAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace ConfigBoundNET
{
    /// <summary>
    /// Marks a property on a <c>[ConfigSection]</c>-annotated type as holding
    /// a secret (connection string, API key, access token, etc.). The
    /// ConfigBoundNET source generator emits a <c>ToString()</c> /
    /// <c>PrintMembers()</c> override that replaces the value with
    /// <c>"***"</c> so secrets do not leak through record-default logging
    /// or explicit <c>config.ToString()</c> calls.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null-valued sensitive properties still render as <c>null</c>, so
    /// missing-config is distinguishable from set-but-redacted at debug time.
    /// </para>
    /// <para>
    /// Scope: affects <c>ToString()</c> only. Structured-logging
    /// destructurers (Serilog <c>{@X}</c>, NLog <c>${object}</c>, etc.)
    /// reach past <c>ToString()</c> via reflection; configure your logger's
    /// type policy separately for those paths.
    /// </para>
    /// </remarks>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Property,
        AllowMultiple = false,
        Inherited = false)]
    [global::System.Diagnostics.Conditional("CONFIGBOUNDNET_KEEP_ATTRIBUTES")]
    internal sealed class SensitiveAttribute : global::System.Attribute
    {
    }
}
