//HintName: MyApp.TurnstileSettings.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591, CA1710

namespace MyApp;

partial class TurnstileSettings
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("Turnstile")]</c>.
    /// </summary>
    public const string SectionName = "Turnstile";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public TurnstileSettings(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_SecretRaw = section["Secret"];
        if (_cb_SecretRaw is not null)
        {
            this.Secret = _cb_SecretRaw;
        }
        var _cb_SiteKeyRaw = section["SiteKey"];
        if (_cb_SiteKeyRaw is not null)
        {
            this.SiteKey = _cb_SiteKeyRaw;
        }
        var _cb_OptionalNoteRaw = section["OptionalNote"];
        if (_cb_OptionalNoteRaw is not null)
        {
            this.OptionalNote = _cb_OptionalNoteRaw;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="TurnstileSettings"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<TurnstileSettings>
    {
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, TurnstileSettings options)
            => Validate(name, SectionName, options);
        
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, string path, TurnstileSettings options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("TurnstileSettings instance was null.");
            }
            
            global::System.Collections.Generic.List<string>? failures = null;
            
            if (string.IsNullOrWhiteSpace(options.Secret))
            {
                (failures ??= new global::System.Collections.Generic.List<string>()).Add("[" + path + ":Secret] is required but was null, empty, or whitespace.");
            }
            if (string.IsNullOrWhiteSpace(options.SiteKey))
            {
                (failures ??= new global::System.Collections.Generic.List<string>()).Add("[" + path + ":SiteKey] is required but was null, empty, or whitespace.");
            }
            if (options.Secret is not null && options.Secret.Length < 32)
            {
                (failures ??= new global::System.Collections.Generic.List<string>()).Add("[" + path + ":Secret]" + " must have minimum length 32.");
            }
            if (options.SiteKey is not null && options.SiteKey.Length < 24)
            {
                (failures ??= new global::System.Collections.Generic.List<string>()).Add("[" + path + ":SiteKey]" + " must have minimum length 24.");
            }
            
            options.ValidateCustom((failures ??= new global::System.Collections.Generic.List<string>()));
            options.ValidateCustom((failures ??= new global::System.Collections.Generic.List<string>()), path);
            
            return failures is null || failures.Count == 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Success
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures);
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
    
    /// <summary>
    /// Path-aware overload of the custom validation hook. Implement this
    /// partial method instead of (or alongside) the single-argument form
    /// when you want to include the full runtime configuration path in
    /// your failure messages — useful for types that can be used as
    /// nested or element configs, where the path differs per usage site.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    /// <param name="path">Full configuration path to this options instance, e.g. <c>"Api:Endpoints:1"</c>.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures, string path);
}

/// <summary>
/// Dependency-injection helpers for <see cref="TurnstileSettings"/>.
/// </summary>
public static class TurnstileSettingsServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="TurnstileSettings"/> to the <c>"Turnstile"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddTurnstileSettings(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(TurnstileSettings.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<TurnstileSettings>, TurnstileSettings.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<TurnstileSettings>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<TurnstileSettings>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<TurnstileSettings>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<TurnstileSettings>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<TurnstileSettings>>(sp),
                    _ => new TurnstileSettings(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<TurnstileSettings>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<TurnstileSettings>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
