//HintName: ConfigBoundNET.ConfigSectionAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace ConfigBoundNET
{
    /// <summary>
    /// Marks a partial record or class as bound to a named configuration section.
    /// The ConfigBoundNET source generator picks up every type with this attribute
    /// and emits:
    /// <list type="bullet">
    ///   <item><description>An <c>IValidateOptions&lt;T&gt;</c> implementation named <c>Validator</c> nested inside the annotated type.</description></item>
    ///   <item><description>A <c>services.Add{TypeName}()</c> extension method that binds the section and wires the validator.</description></item>
    ///   <item><description>Build-time diagnostics for misuse (missing <c>partial</c>, empty section name, etc.).</description></item>
    /// </list>
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct,
        AllowMultiple = false,
        Inherited = false)]
    [global::System.Diagnostics.Conditional("CONFIGBOUNDNET_KEEP_ATTRIBUTES")]
    internal sealed class ConfigSectionAttribute : global::System.Attribute
    {
        /// <summary>
        /// Initializes a new instance with an inferred section name.
        /// The generator derives the name from the type name by stripping
        /// common suffixes (<c>Config</c>, <c>Options</c>, <c>Settings</c>,
        /// <c>Configuration</c>). E.g. <c>DbConfig</c> becomes <c>"Db"</c>.
        /// </summary>
        public ConfigSectionAttribute()
        {
            SectionName = string.Empty;
        }

        /// <summary>Initializes a new instance of the <see cref="ConfigSectionAttribute"/> class.</summary>
        /// <param name="sectionName">
        /// The configuration section name, e.g. <c>"Db"</c> for a section that lives
        /// at the top level of appsettings.json, or <c>"Services:Payments"</c> for
        /// a nested section.
        /// </param>
        public ConfigSectionAttribute(string sectionName)
        {
            SectionName = sectionName;
        }

        /// <summary>Gets the configuration section name supplied at construction time, or empty if inferred.</summary>
        public string SectionName { get; }
    }
}
