//HintName: MyApp.OptionalConfig.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591

namespace MyApp;

partial record OptionalConfig
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("Opt")]</c>.
    /// </summary>
    public const string SectionName = "Opt";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    public OptionalConfig(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_RequiredRaw = section["Required"];
        if (_cb_RequiredRaw is not null)
        {
            this.Required = _cb_RequiredRaw;
        }
        var _cb_OptionalStringRaw = section["OptionalString"];
        if (_cb_OptionalStringRaw is not null)
        {
            this.OptionalString = _cb_OptionalStringRaw;
        }
        var _cb_OptionalIntRaw = section["OptionalInt"];
        if (_cb_OptionalIntRaw is not null && int.TryParse(_cb_OptionalIntRaw, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_OptionalIntParsed))
        {
            this.OptionalInt = _cb_OptionalIntParsed;
        }
        var _cb_OptionalBoolRaw = section["OptionalBool"];
        if (_cb_OptionalBoolRaw is not null && bool.TryParse(_cb_OptionalBoolRaw, out var _cb_OptionalBoolParsed))
        {
            this.OptionalBool = _cb_OptionalBoolParsed;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="OptionalConfig"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<OptionalConfig>
    {
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, OptionalConfig options)
            => Validate(name, SectionName, options);
        
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, string path, OptionalConfig options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("OptionalConfig instance was null.");
            }
            
            var failures = new global::System.Collections.Generic.List<string>();
            
            if (string.IsNullOrWhiteSpace(options.Required))
            {
                failures.Add("[" + path + ":Required] is required but was null, empty, or whitespace.");
            }
            
            options.ValidateCustom(failures);
            options.ValidateCustom(failures, path);
            
            return failures.Count > 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures)
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Success;
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
    
    /// <summary>
    /// Path-aware overload of the custom validation hook. Implement this
    /// partial method instead of (or alongside) the single-argument form
    /// when you want to include the full runtime configuration path in
    /// your failure messages — useful for types that can be used as
    /// nested or element configs, where the path differs per usage site.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    /// <param name="path">Full configuration path to this options instance, e.g. <c>"Api:Endpoints:1"</c>.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures, string path);
}

/// <summary>
/// Dependency-injection helpers for <see cref="OptionalConfig"/>.
/// </summary>
public static class OptionalConfigServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="OptionalConfig"/> to the <c>"Opt"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddOptionalConfig(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(OptionalConfig.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<OptionalConfig>, OptionalConfig.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<OptionalConfig>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<OptionalConfig>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<OptionalConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<OptionalConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<OptionalConfig>>(sp),
                    _ => new OptionalConfig(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<OptionalConfig>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<OptionalConfig>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
