//HintName: MyApp.TestConfig.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591

namespace MyApp;

partial record TestConfig
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("Test")]</c>.
    /// </summary>
    public const string SectionName = "Test";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    public TestConfig(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_PortRaw = section["Port"];
        if (_cb_PortRaw is not null && int.TryParse(_cb_PortRaw, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_PortParsed))
        {
            this.Port = _cb_PortParsed;
        }
        var _cb_EndpointRaw = section["Endpoint"];
        if (_cb_EndpointRaw is not null)
        {
            this.Endpoint = _cb_EndpointRaw;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="TestConfig"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<TestConfig>
    {
        private static readonly global::System.Text.RegularExpressions.Regex _cb_Regex_Endpoint = new global::System.Text.RegularExpressions.Regex(@"^https?://", global::System.Text.RegularExpressions.RegexOptions.Compiled);
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, TestConfig options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("TestConfig instance was null.");
            }
            
            var failures = new global::System.Collections.Generic.List<string>();
            
            if (string.IsNullOrWhiteSpace(options.Endpoint))
            {
                failures.Add("[Test:Endpoint] is required but was null, empty, or whitespace.");
            }
            if (options.Port < 1 || options.Port > 65535)
            {
                failures.Add("Port [Test:Port] must be between 1 and 65535.");
            }
            if (options.Endpoint is not null && !_cb_Regex_Endpoint.IsMatch(options.Endpoint))
            {
                failures.Add("Must be an http(s) URL.");
            }
            
            options.ValidateCustom(failures);
            
            return failures.Count > 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures)
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Success;
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
}

/// <summary>
/// Dependency-injection helpers for <see cref="TestConfig"/>.
/// </summary>
public static class TestConfigServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="TestConfig"/> to the <c>"Test"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddTestConfig(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(TestConfig.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<TestConfig>, TestConfig.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<TestConfig>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<TestConfig>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<TestConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<TestConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<TestConfig>>(sp),
                    _ => new TestConfig(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<TestConfig>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<TestConfig>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
