//HintName: MyApp.ApiConfig.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591

namespace MyApp;

partial record ApiConfig
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("Api")]</c>.
    /// </summary>
    public const string SectionName = "Api";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    public ApiConfig(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_EndpointsSection = section.GetSection("Endpoints");
        var _cb_EndpointsList = new global::System.Collections.Generic.List<global::MyApp.EndpointConfig>();
        foreach (var _cb_EndpointsChild in _cb_EndpointsSection.GetChildren())
        {
            _cb_EndpointsList.Add(new global::MyApp.EndpointConfig(_cb_EndpointsChild));
        }
        if (_cb_EndpointsList.Count > 0)
        {
            this.Endpoints = _cb_EndpointsList;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="ApiConfig"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<ApiConfig>
    {
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, ApiConfig options)
            => Validate(name, SectionName, options);
        
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, string path, ApiConfig options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("ApiConfig instance was null.");
            }
            
            var failures = new global::System.Collections.Generic.List<string>();
            
            if (options.Endpoints is null)
            {
                failures.Add("[" + path + ":Endpoints] is required but was null.");
            }
            if (options.Endpoints is not null && options.Endpoints.Count < 1)
            {
                failures.Add("[" + path + ":Endpoints]" + " must have minimum length 1.");
            }
            if (options.Endpoints is not null)
            {
                int _cb_EndpointsIdx = 0;
                foreach (var _cb_EndpointsItem in options.Endpoints)
                {
                    if (_cb_EndpointsItem is not null)
                    {
                        var _cb_EndpointsItemPath = path + ":Endpoints:" + _cb_EndpointsIdx.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                        var _cb_EndpointsItemResult = new global::MyApp.EndpointConfig.Validator().Validate(name, _cb_EndpointsItemPath, _cb_EndpointsItem);
                        if (_cb_EndpointsItemResult.Failed)
                        {
                            failures.AddRange(_cb_EndpointsItemResult.Failures);
                        }
                    }
                    _cb_EndpointsIdx++;
                }
            }
            
            options.ValidateCustom(failures);
            options.ValidateCustom(failures, path);
            
            return failures.Count > 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures)
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Success;
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
    
    /// <summary>
    /// Path-aware overload of the custom validation hook. Implement this
    /// partial method instead of (or alongside) the single-argument form
    /// when you want to include the full runtime configuration path in
    /// your failure messages — useful for types that can be used as
    /// nested or element configs, where the path differs per usage site.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    /// <param name="path">Full configuration path to this options instance, e.g. <c>"Api:Endpoints:1"</c>.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures, string path);
}

/// <summary>
/// Dependency-injection helpers for <see cref="ApiConfig"/>.
/// </summary>
public static class ApiConfigServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="ApiConfig"/> to the <c>"Api"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddApiConfig(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(ApiConfig.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<ApiConfig>, ApiConfig.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<ApiConfig>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<ApiConfig>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<ApiConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<ApiConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<ApiConfig>>(sp),
                    _ => new ApiConfig(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<ApiConfig>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<ApiConfig>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
