//HintName: MyApp.TypesConfig.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591

namespace MyApp;

partial record TypesConfig
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("Types")]</c>.
    /// </summary>
    public const string SectionName = "Types";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    public TypesConfig(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_TextRaw = section["Text"];
        if (_cb_TextRaw is not null)
        {
            this.Text = _cb_TextRaw;
        }
        var _cb_EnabledRaw = section["Enabled"];
        if (_cb_EnabledRaw is not null && bool.TryParse(_cb_EnabledRaw, out var _cb_EnabledParsed))
        {
            this.Enabled = _cb_EnabledParsed;
        }
        var _cb_SmallNumRaw = section["SmallNum"];
        if (_cb_SmallNumRaw is not null && byte.TryParse(_cb_SmallNumRaw, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_SmallNumParsed))
        {
            this.SmallNum = _cb_SmallNumParsed;
        }
        var _cb_CountRaw = section["Count"];
        if (_cb_CountRaw is not null && int.TryParse(_cb_CountRaw, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_CountParsed))
        {
            this.Count = _cb_CountParsed;
        }
        var _cb_BigNumRaw = section["BigNum"];
        if (_cb_BigNumRaw is not null && long.TryParse(_cb_BigNumRaw, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_BigNumParsed))
        {
            this.BigNum = _cb_BigNumParsed;
        }
        var _cb_RatioRaw = section["Ratio"];
        if (_cb_RatioRaw is not null && double.TryParse(_cb_RatioRaw, global::System.Globalization.NumberStyles.Float, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_RatioParsed))
        {
            this.Ratio = _cb_RatioParsed;
        }
        var _cb_PriceRaw = section["Price"];
        if (_cb_PriceRaw is not null && decimal.TryParse(_cb_PriceRaw, global::System.Globalization.NumberStyles.Float, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_PriceParsed))
        {
            this.Price = _cb_PriceParsed;
        }
        var _cb_TenantIdRaw = section["TenantId"];
        if (_cb_TenantIdRaw is not null && global::System.Guid.TryParse(_cb_TenantIdRaw, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_TenantIdParsed))
        {
            this.TenantId = _cb_TenantIdParsed;
        }
        var _cb_TimeoutRaw = section["Timeout"];
        if (_cb_TimeoutRaw is not null && global::System.TimeSpan.TryParse(_cb_TimeoutRaw, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_TimeoutParsed))
        {
            this.Timeout = _cb_TimeoutParsed;
        }
        var _cb_CreatedAtRaw = section["CreatedAt"];
        if (_cb_CreatedAtRaw is not null && global::System.DateTime.TryParse(_cb_CreatedAtRaw, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.RoundtripKind, out var _cb_CreatedAtParsed))
        {
            this.CreatedAt = _cb_CreatedAtParsed;
        }
        var _cb_DeployedAtRaw = section["DeployedAt"];
        if (_cb_DeployedAtRaw is not null && global::System.DateTimeOffset.TryParse(_cb_DeployedAtRaw, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.RoundtripKind, out var _cb_DeployedAtParsed))
        {
            this.DeployedAt = _cb_DeployedAtParsed;
        }
        var _cb_EndpointRaw = section["Endpoint"];
        if (_cb_EndpointRaw is not null && global::System.Uri.TryCreate(_cb_EndpointRaw, global::System.UriKind.Absolute, out var _cb_EndpointParsed))
        {
            this.Endpoint = _cb_EndpointParsed;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="TypesConfig"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<TypesConfig>
    {
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, TypesConfig options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("TypesConfig instance was null.");
            }
            
            var failures = new global::System.Collections.Generic.List<string>();
            
            if (string.IsNullOrWhiteSpace(options.Text))
            {
                failures.Add("[Types:Text] is required but was null, empty, or whitespace.");
            }
            if (options.Endpoint is null)
            {
                failures.Add("[Types:Endpoint] is required but was null.");
            }
            
            options.ValidateCustom(failures);
            
            return failures.Count > 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures)
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Success;
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
}

/// <summary>
/// Dependency-injection helpers for <see cref="TypesConfig"/>.
/// </summary>
public static class TypesConfigServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="TypesConfig"/> to the <c>"Types"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddTypesConfig(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(TypesConfig.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<TypesConfig>, TypesConfig.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<TypesConfig>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<TypesConfig>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<TypesConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<TypesConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<TypesConfig>>(sp),
                    _ => new TypesConfig(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<TypesConfig>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<TypesConfig>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
