//HintName: MyApp.PasswordConfig.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591, CA1710

namespace MyApp;

partial record PasswordConfig
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("Pwd")]</c>.
    /// </summary>
    public const string SectionName = "Pwd";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    public PasswordConfig(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_DefaultPasswordRaw = section["DefaultPassword"];
        if (_cb_DefaultPasswordRaw is not null)
        {
            this.DefaultPassword = _cb_DefaultPasswordRaw;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="PasswordConfig"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<PasswordConfig>
    {
        private static readonly global::System.Text.RegularExpressions.Regex _cb_Regex_DefaultPassword = new global::System.Text.RegularExpressions.Regex(@"^(?=.*[A-Z])(?=.*[0-9])", global::System.Text.RegularExpressions.RegexOptions.Compiled);
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, PasswordConfig options)
            => Validate(name, SectionName, options);
        
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, string path, PasswordConfig options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("PasswordConfig instance was null.");
            }
            
            global::System.Collections.Generic.List<string>? failures = null;
            
            if (string.IsNullOrWhiteSpace(options.DefaultPassword))
            {
                (failures ??= new global::System.Collections.Generic.List<string>()).Add("[" + path + ":DefaultPassword] is required but was null, empty, or whitespace.");
            }
            if (options.DefaultPassword is not null && options.DefaultPassword.Length < 8)
            {
                (failures ??= new global::System.Collections.Generic.List<string>()).Add("[" + path + ":DefaultPassword]" + " must have minimum length 8.");
            }
            if (options.DefaultPassword is not null && options.DefaultPassword.Length > 128)
            {
                (failures ??= new global::System.Collections.Generic.List<string>()).Add("[" + path + ":DefaultPassword]" + " must have maximum length 128.");
            }
            if (options.DefaultPassword is not null && !_cb_Regex_DefaultPassword.IsMatch(options.DefaultPassword))
            {
                (failures ??= new global::System.Collections.Generic.List<string>()).Add("[" + path + ":DefaultPassword]" + " does not match the required pattern.");
            }
            
            options.ValidateCustom((failures ??= new global::System.Collections.Generic.List<string>()));
            options.ValidateCustom((failures ??= new global::System.Collections.Generic.List<string>()), path);
            
            return failures is null || failures.Count == 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Success
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures);
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
    
    /// <summary>
    /// Path-aware overload of the custom validation hook. Implement this
    /// partial method instead of (or alongside) the single-argument form
    /// when you want to include the full runtime configuration path in
    /// your failure messages — useful for types that can be used as
    /// nested or element configs, where the path differs per usage site.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    /// <param name="path">Full configuration path to this options instance, e.g. <c>"Api:Endpoints:1"</c>.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures, string path);
}

/// <summary>
/// Dependency-injection helpers for <see cref="PasswordConfig"/>.
/// </summary>
public static class PasswordConfigServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="PasswordConfig"/> to the <c>"Pwd"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddPasswordConfig(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(PasswordConfig.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<PasswordConfig>, PasswordConfig.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<PasswordConfig>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<PasswordConfig>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<PasswordConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<PasswordConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<PasswordConfig>>(sp),
                    _ => new PasswordConfig(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<PasswordConfig>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<PasswordConfig>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
