//HintName: MyApp.DbConfig.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591, CA1710

namespace MyApp;

[global::System.Diagnostics.CodeAnalysis.SuppressMessage(
    "Naming", "CA1710:Identifiers should have correct suffix",
    Justification = "Type is a [ConfigSection] record with an explicit IReadOnlyDictionary<string, object?> impl emitted for [Sensitive]-redacted structured logging. Its primary role is config, not collection.")]
partial record DbConfig : global::System.Collections.Generic.IReadOnlyDictionary<string, object?>
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("Db")]</c>.
    /// </summary>
    public const string SectionName = "Db";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    public DbConfig(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_ConnRaw = section["Conn"];
        if (_cb_ConnRaw is not null)
        {
            this.Conn = _cb_ConnRaw;
        }
        var _cb_TokenRaw = section["Token"];
        if (_cb_TokenRaw is not null && global::System.Guid.TryParse(_cb_TokenRaw, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_TokenParsed))
        {
            this.Token = _cb_TokenParsed;
        }
        var _cb_PortRaw = section["Port"];
        if (_cb_PortRaw is not null && int.TryParse(_cb_PortRaw, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_PortParsed))
        {
            this.Port = _cb_PortParsed;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="DbConfig"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<DbConfig>
    {
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, DbConfig options)
            => Validate(name, SectionName, options);
        
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, string path, DbConfig options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("DbConfig instance was null.");
            }
            
            global::System.Collections.Generic.List<string>? failures = null;
            
            if (string.IsNullOrWhiteSpace(options.Conn))
            {
                (failures ??= new global::System.Collections.Generic.List<string>()).Add("[" + path + ":Conn] is required but was null, empty, or whitespace.");
            }
            
            options.ValidateCustom((failures ??= new global::System.Collections.Generic.List<string>()));
            options.ValidateCustom((failures ??= new global::System.Collections.Generic.List<string>()), path);
            
            return failures is null || failures.Count == 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Success
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures);
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
    
    /// <summary>
    /// Path-aware overload of the custom validation hook. Implement this
    /// partial method instead of (or alongside) the single-argument form
    /// when you want to include the full runtime configuration path in
    /// your failure messages — useful for types that can be used as
    /// nested or element configs, where the path differs per usage site.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    /// <param name="path">Full configuration path to this options instance, e.g. <c>"Api:Endpoints:1"</c>.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures, string path);
    
    /// <summary>
    /// Record <c>PrintMembers</c> override emitted by ConfigBoundNET because
    /// at least one property is decorated with <c>[Sensitive]</c>. Replaces
    /// those property values with <c>"***"</c> so <c>ToString()</c>,
    /// <c>logger.LogInformation("{Config}", cfg)</c>, and similar callers
    /// don't leak secrets.
    /// </summary>
    protected virtual bool PrintMembers(global::System.Text.StringBuilder builder)
    {
        builder.Append("Conn = ");
        builder.Append(this.Conn is null ? "null" : "***");
        builder.Append(", Token = ");
        builder.Append("***");
        builder.Append(", Port = ");
        builder.Append(this.Port);
        return true;
    }
    
    // ── IReadOnlyDictionary<string, object?> implementation (explicit).
    //    Drives transparent redaction in structured-logging destructurers that
    //    detect the interface (Serilog, System.Text.Json, NLog, etc.) without
    //    any reflection on the type's properties.
    private static readonly string[] _cb_Keys = new[]
    {
        "Conn",
        "Token",
        "Port",
    };
    
    int global::System.Collections.Generic.IReadOnlyCollection<global::System.Collections.Generic.KeyValuePair<string, object?>>.Count => 3;
    
    object? global::System.Collections.Generic.IReadOnlyDictionary<string, object?>.this[string key] => key switch
    {
        "Conn" => this.Conn is null ? null : "***",
        "Token" => "***",
        "Port" => this.Port,
        _ => throw new global::System.Collections.Generic.KeyNotFoundException(key),
    };
    
    global::System.Collections.Generic.IEnumerable<string> global::System.Collections.Generic.IReadOnlyDictionary<string, object?>.Keys => _cb_Keys;
    
    global::System.Collections.Generic.IEnumerable<object?> global::System.Collections.Generic.IReadOnlyDictionary<string, object?>.Values
    {
        get
        {
            yield return this.Conn is null ? null : "***";
            yield return "***";
            yield return this.Port;
        }
    }
    
    bool global::System.Collections.Generic.IReadOnlyDictionary<string, object?>.ContainsKey(string key) => key is "Conn" or "Token" or "Port";
    
    bool global::System.Collections.Generic.IReadOnlyDictionary<string, object?>.TryGetValue(string key, out object? value)
    {
        switch (key)
        {
            case "Conn": value = this.Conn is null ? null : "***"; return true;
            case "Token": value = "***"; return true;
            case "Port": value = this.Port; return true;
            default: value = null; return false;
        }
    }
    
    global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>> global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object?>>.GetEnumerator()
    {
        yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("Conn", this.Conn is null ? null : "***");
        yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("Token", "***");
        yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("Port", this.Port);
    }
    
    global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator()
        => ((global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object?>>)this).GetEnumerator();
}

/// <summary>
/// Dependency-injection helpers for <see cref="DbConfig"/>.
/// </summary>
public static class DbConfigServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="DbConfig"/> to the <c>"Db"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDbConfig(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(DbConfig.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<DbConfig>, DbConfig.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<DbConfig>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<DbConfig>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<DbConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<DbConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<DbConfig>>(sp),
                    _ => new DbConfig(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<DbConfig>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<DbConfig>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
