//HintName: ConfigBoundNET.JsonSchema.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable

namespace ConfigBoundNET;

/// <summary>
/// Exposes the JSON Schema (draft 2020-12) describing every
/// <c>[ConfigSection]</c>-annotated type in this assembly. Reference it
/// from your <c>appsettings.json</c> via <c>"$schema":</c> to get
/// IntelliSense and validation red-squiggles in VS Code, Visual Studio,
/// and Rider.
/// </summary>
public static class ConfigBoundJsonSchema
{
    /// <summary>The JSON Schema document, emitted at build time.</summary>
    public const string Json = @"{
  ""$schema"": ""https://json-schema.org/draft/2020-12/schema"",
  ""title"": ""ConfigBoundNET generated schema"",
  ""type"": ""object"",
  ""additionalProperties"": true,
  ""properties"": {
    ""Api"": {
      ""type"": ""object"",
      ""additionalProperties"": false,
      ""properties"": {
        ""Endpoints"": {
          ""type"": ""array"",
          ""items"": {
            ""type"": ""object"",
            ""additionalProperties"": false,
            ""properties"": {
              ""Url"": {
                ""type"": ""string""
              },
              ""Port"": {
                ""type"": ""integer"",
                ""minimum"": 1,
                ""maximum"": 65535
              }
            },
            ""required"": [""Url""]
          },
          ""minItems"": 1
        }
      },
      ""required"": [""Endpoints""]
    },
    ""__endpoint__"": {
      ""type"": ""object"",
      ""additionalProperties"": false,
      ""properties"": {
        ""Url"": {
          ""type"": ""string""
        },
        ""Port"": {
          ""type"": ""integer"",
          ""minimum"": 1,
          ""maximum"": 65535
        }
      },
      ""required"": [""Url""]
    }
  }
}";
}
