//HintName: MyApp.ContactConfig.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591

namespace MyApp;

partial record ContactConfig
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("Contact")]</c>.
    /// </summary>
    public const string SectionName = "Contact";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    public ContactConfig(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_WebsiteRaw = section["Website"];
        if (_cb_WebsiteRaw is not null)
        {
            this.Website = _cb_WebsiteRaw;
        }
        var _cb_AdminEmailRaw = section["AdminEmail"];
        if (_cb_AdminEmailRaw is not null)
        {
            this.AdminEmail = _cb_AdminEmailRaw;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="ContactConfig"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<ContactConfig>
    {
        private static readonly global::System.Text.RegularExpressions.Regex _cb_Regex_Email_AdminEmail = new global::System.Text.RegularExpressions.Regex(@"^[^@\s]+@[^@\s]+\.[^@\s]+$", global::System.Text.RegularExpressions.RegexOptions.Compiled);
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, ContactConfig options)
            => Validate(name, SectionName, options);
        
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, string path, ContactConfig options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("ContactConfig instance was null.");
            }
            
            var failures = new global::System.Collections.Generic.List<string>();
            
            if (string.IsNullOrWhiteSpace(options.Website))
            {
                failures.Add("[" + path + ":Website] is required but was null, empty, or whitespace.");
            }
            if (string.IsNullOrWhiteSpace(options.AdminEmail))
            {
                failures.Add("[" + path + ":AdminEmail] is required but was null, empty, or whitespace.");
            }
            if (options.Website is not null && !global::System.Uri.TryCreate(options.Website, global::System.UriKind.Absolute, out _))
            {
                failures.Add("[" + path + ":Website]" + " is not a valid absolute URL.");
            }
            if (options.AdminEmail is not null && !_cb_Regex_Email_AdminEmail.IsMatch(options.AdminEmail))
            {
                failures.Add("[" + path + ":AdminEmail]" + " is not a valid email address.");
            }
            
            options.ValidateCustom(failures);
            options.ValidateCustom(failures, path);
            
            return failures.Count > 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures)
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Success;
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
    
    /// <summary>
    /// Path-aware overload of the custom validation hook. Implement this
    /// partial method instead of (or alongside) the single-argument form
    /// when you want to include the full runtime configuration path in
    /// your failure messages — useful for types that can be used as
    /// nested or element configs, where the path differs per usage site.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    /// <param name="path">Full configuration path to this options instance, e.g. <c>"Api:Endpoints:1"</c>.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures, string path);
}

/// <summary>
/// Dependency-injection helpers for <see cref="ContactConfig"/>.
/// </summary>
public static class ContactConfigServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="ContactConfig"/> to the <c>"Contact"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddContactConfig(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(ContactConfig.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<ContactConfig>, ContactConfig.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<ContactConfig>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<ContactConfig>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<ContactConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<ContactConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<ContactConfig>>(sp),
                    _ => new ContactConfig(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<ContactConfig>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<ContactConfig>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
