//HintName: MyApp.EndpointConfig.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591, CA1710

namespace MyApp;

partial record EndpointConfig
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("__endpoint__")]</c>.
    /// </summary>
    public const string SectionName = "__endpoint__";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    public EndpointConfig(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_UrlRaw = section["Url"];
        if (_cb_UrlRaw is not null)
        {
            this.Url = _cb_UrlRaw;
        }
        var _cb_TimeoutRaw = section["Timeout"];
        if (_cb_TimeoutRaw is not null && global::System.TimeSpan.TryParse(_cb_TimeoutRaw, global::System.Globalization.CultureInfo.InvariantCulture, out var _cb_TimeoutParsed))
        {
            this.Timeout = _cb_TimeoutParsed;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="EndpointConfig"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<EndpointConfig>
    {
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, EndpointConfig options)
            => Validate(name, SectionName, options);
        
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, string path, EndpointConfig options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("EndpointConfig instance was null.");
            }
            
            global::System.Collections.Generic.List<string>? failures = null;
            
            if (string.IsNullOrWhiteSpace(options.Url))
            {
                (failures ??= new global::System.Collections.Generic.List<string>()).Add("[" + path + ":Url] is required but was null, empty, or whitespace.");
            }
            
            options.ValidateCustom((failures ??= new global::System.Collections.Generic.List<string>()));
            options.ValidateCustom((failures ??= new global::System.Collections.Generic.List<string>()), path);
            
            return failures is null || failures.Count == 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Success
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures);
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
    
    /// <summary>
    /// Path-aware overload of the custom validation hook. Implement this
    /// partial method instead of (or alongside) the single-argument form
    /// when you want to include the full runtime configuration path in
    /// your failure messages — useful for types that can be used as
    /// nested or element configs, where the path differs per usage site.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    /// <param name="path">Full configuration path to this options instance, e.g. <c>"Api:Endpoints:1"</c>.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures, string path);
}

/// <summary>
/// Dependency-injection helpers for <see cref="EndpointConfig"/>.
/// </summary>
public static class EndpointConfigServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="EndpointConfig"/> to the <c>"__endpoint__"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddEndpointConfig(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(EndpointConfig.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<EndpointConfig>, EndpointConfig.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<EndpointConfig>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<EndpointConfig>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<EndpointConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<EndpointConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<EndpointConfig>>(sp),
                    _ => new EndpointConfig(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<EndpointConfig>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<EndpointConfig>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
