//HintName: ConfigBoundNET.AggregateRegistration.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591, CA1710

namespace ConfigBoundNET;

/// <summary>
/// Generated convenience extensions that register every <c>[ConfigSection]</c>-
/// annotated type discovered in the containing assembly in a single call.
/// </summary>
public static class ConfigBoundSectionRegistrations
{
    /// <summary>
    /// Registers every <c>[ConfigSection]</c>-annotated type in this assembly.
    /// Top-level types (neither flagged with <c>IsNestedOnly = true</c> nor
    /// referenced as a nested property of another <c>[ConfigSection]</c> in this
    /// compilation) are registered unconditionally — a missing root section
    /// becomes a validation failure (lazily on first <c>IOptions&lt;T&gt;.Value</c>
    /// read, or eagerly at host start when <paramref name="validateOnStart"/> is
    /// <see langword="true"/>). Nested-only types stay gated behind a
    /// <c>ConfigurationExtensions.Exists(…)</c> check so throwaway section names
    /// (e.g. <c>__endpoint__</c>) don't spuriously fail validation on startup.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <param name="validateOnStart">
    /// When <see langword="true"/>, chains
    /// <c>AddOptions&lt;T&gt;().ValidateOnStart()</c> for every registered section so
    /// misconfiguration fails at host start instead of on first
    /// <c>IOptions&lt;T&gt;.Value</c> read. Only applies to sections that pass the
    /// <c>.Exists()</c> gate; absent sections remain silently skipped. Default
    /// <see langword="false"/> preserves the v2.x behaviour where validation
    /// fires lazily on first resolution.
    /// </param>
    /// <returns>The original <paramref name="services"/> instance, enabling fluent chaining.</returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddConfigBoundSections(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        bool validateOnStart = false)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        global::MyApp.OptionalConfigServiceCollectionExtensions.AddOptionalConfig(services, configuration);
        if (validateOnStart)
        {
            global::Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.ValidateOnStart<global::MyApp.OptionalConfig>(
                global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions<global::MyApp.OptionalConfig>(services));
        }
        
        return services;
    }
}
