//HintName: MyApp.AuthConfig.ConfigBound.g.cs
// <auto-generated>
//     This file was generated by ConfigBoundNET.
//     Changes to this file will be lost when the generator re-runs.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591

namespace MyApp;

partial record AuthConfig
{
    /// <summary>
    /// The configuration section name declared via <c>[ConfigSection("Auth")]</c>.
    /// </summary>
    public const string SectionName = "Auth";
    
    /// <summary>
    /// Reflection-free constructor generated by ConfigBoundNET.
    /// Reads values from the supplied configuration section and copies
    /// them into a new instance, preserving any field-initializer defaults
    /// for keys that are absent from the section.
    /// </summary>
    /// <param name="section">The configuration section to read from.</param>
    public AuthConfig(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
    {
        if (section is null) throw new global::System.ArgumentNullException(nameof(section));
        
        var _cb_SecretRaw = section["Secret"];
        if (_cb_SecretRaw is not null)
        {
            this.Secret = _cb_SecretRaw;
        }
        var _cb_IssuerRaw = section["Issuer"];
        if (_cb_IssuerRaw is not null)
        {
            this.Issuer = _cb_IssuerRaw;
        }
    }
    
    /// <summary>
    /// Auto-generated validator for <see cref="AuthConfig"/>.
    /// </summary>
    /// <remarks>
    /// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly
    /// at startup if <c>ValidateOnStart()</c> is chained on the options builder.
    /// </remarks>
    public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<AuthConfig>
    {
        public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, AuthConfig options)
        {
            if (options is null)
            {
                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail("AuthConfig instance was null.");
            }
            
            var failures = new global::System.Collections.Generic.List<string>();
            
            if (string.IsNullOrWhiteSpace(options.Secret))
            {
                failures.Add("[Auth:Secret] is required but was null, empty, or whitespace.");
            }
            if (string.IsNullOrWhiteSpace(options.Issuer))
            {
                failures.Add("[Auth:Issuer] is required but was null, empty, or whitespace.");
            }
            if (options.Secret is not null && options.Secret.Length < 32)
            {
                failures.Add("[Auth:Secret] must have minimum length 32.");
            }
            if (options.Issuer is not null && options.Issuer.Length > 100)
            {
                failures.Add("[Auth:Issuer] must have maximum length 100.");
            }
            
            options.ValidateCustom(failures);
            
            return failures.Count > 0
                ? global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures)
                : global::Microsoft.Extensions.Options.ValidateOptionsResult.Success;
        }
    }
    
    /// <summary>
    /// Optional hook for custom cross-field validation. Implement this
    /// partial method on your config type to add validation rules that
    /// cannot be expressed with DataAnnotations alone.
    /// Called after all generated checks.
    /// </summary>
    /// <param name="failures">Mutable list of failure messages. Add to it to report errors.</param>
    partial void ValidateCustom(global::System.Collections.Generic.List<string> failures);
}

/// <summary>
/// Dependency-injection helpers for <see cref="AuthConfig"/>.
/// </summary>
public static class AuthConfigServiceCollectionExtensions
{
    /// <summary>
    /// Binds <see cref="AuthConfig"/> to the <c>"Auth"</c> configuration section and registers the generated validator.
    /// </summary>
    /// <param name="services">The service collection to register into.</param>
    /// <param name="configuration">The application's <c>IConfiguration</c> root or parent section.</param>
    /// <returns>
    /// The original <paramref name="services"/> instance, enabling fluent chaining.
    /// </returns>
    /// <exception cref="global::System.ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="configuration"/> is <see langword="null"/>.</exception>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAuthConfig(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        if (services is null) throw new global::System.ArgumentNullException(nameof(services));
        if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));
        
        var section = configuration.GetSection(AuthConfig.SectionName);
        
        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<AuthConfig>, AuthConfig.Validator>());
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<AuthConfig>>(sp =>
                new global::ConfigBoundNET.ConfigBoundOptionsFactory<AuthConfig>(
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<AuthConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<AuthConfig>>(sp),
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<AuthConfig>>(sp),
                    _ => new AuthConfig(section))));
        
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
            services,
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<AuthConfig>>(
                new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<AuthConfig>(
                    global::Microsoft.Extensions.Options.Options.DefaultName,
                    section)));
        
        return services;
    }
}
