//HintName: ConfigBoundNET.ConfigBoundOptionsFactory.g.cs
// <auto-generated/>
#nullable enable

namespace ConfigBoundNET
{
    /// <summary>
    /// Generic <c>IOptionsFactory&lt;T&gt;</c> shim that lets ConfigBoundNET
    /// supply its own instance constructor while keeping the standard
    /// configure / post-configure / validate pipeline intact.
    /// </summary>
    /// <typeparam name="T">The options type.</typeparam>
    /// <remarks>
    /// The <c>[DynamicallyAccessedMembers]</c> annotation on <c>T</c>
    /// matches the one on the base <c>OptionsFactory&lt;TOptions&gt;</c>'s
    /// type parameter. Without it, the trim analyzer raises IL2091 at every
    /// generated registration site, since our generic parameter would be
    /// flowing into a stricter target.
    /// </remarks>
    internal sealed class ConfigBoundOptionsFactory<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T> : global::Microsoft.Extensions.Options.OptionsFactory<T>
        where T : class
    {
        private readonly global::System.Func<string, T> _instanceFactory;

        public ConfigBoundOptionsFactory(
            global::System.Collections.Generic.IEnumerable<global::Microsoft.Extensions.Options.IConfigureOptions<T>> setups,
            global::System.Collections.Generic.IEnumerable<global::Microsoft.Extensions.Options.IPostConfigureOptions<T>> postConfigures,
            global::System.Collections.Generic.IEnumerable<global::Microsoft.Extensions.Options.IValidateOptions<T>> validations,
            global::System.Func<string, T> instanceFactory)
            : base(setups, postConfigures, validations)
        {
            _instanceFactory = instanceFactory;
        }

        /// <summary>
        /// Construct the options instance via the supplied factory delegate
        /// instead of <c>Activator.CreateInstance&lt;T&gt;()</c>. The base
        /// <c>Create</c> still runs all <c>IConfigureOptions&lt;T&gt;</c>,
        /// <c>IPostConfigureOptions&lt;T&gt;</c>, and validation passes after
        /// this returns, so users can still layer behaviour on top —
        /// the only constraint is that any post-construction configure step
        /// cannot mutate <c>init</c>-only properties (a C# language rule, not
        /// a ConfigBoundNET limitation).
        /// </summary>
        protected override T CreateInstance(string name) => _instanceFactory(name);
    }
}
