// Copyright (c) ConfigBoundNET contributors. Licensed under the GPL-3 License.

using ConfigBoundNET.Example;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;

// ─────────────────────────────────────────────────────────────────────────────
// 1. Build a host using the standard Generic Host pattern.
//    CreateApplicationBuilder wires up appsettings.json, environment variables,
//    and command line arguments into builder.Configuration automatically.
// ─────────────────────────────────────────────────────────────────────────────
var builder = Host.CreateApplicationBuilder(args);

// ─────────────────────────────────────────────────────────────────────────────
// 2. Register the strongly-typed config with a single call. The extension
//    method AddDbConfig is generated by ConfigBoundNET from the [ConfigSection]
//    attribute on DbConfig below — it:
//
//      • binds the "Db" section to a DbConfig instance,
//      • registers the generated DbConfig.Validator (IValidateOptions<DbConfig>),
//      • and wires change-token propagation so IOptionsMonitor picks up reloads.
//
//    We chain ValidateOnStart() so missing values fail fast when the host
//    starts rather than on first IOptions<T> resolution.
// ─────────────────────────────────────────────────────────────────────────────
builder.Services
    .AddDbConfig(builder.Configuration)
    .AddOptions<DbConfig>()
    .ValidateOnStart();

using var app = builder.Build();

// ─────────────────────────────────────────────────────────────────────────────
// 3. Resolve the fully validated instance and use it.
// ─────────────────────────────────────────────────────────────────────────────
var dbConfig = app.Services.GetRequiredService<IOptions<DbConfig>>().Value;

System.Console.WriteLine($"[{DbConfig.SectionName}] Conn                   = {dbConfig.Conn}");
System.Console.WriteLine($"[{DbConfig.SectionName}] CommandTimeoutSeconds  = {dbConfig.CommandTimeoutSeconds}");

namespace ConfigBoundNET.Example
{
    /// <summary>
    /// Strongly-typed view of the <c>"Db"</c> configuration section.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Because this type is marked with <c>[ConfigSection("Db")]</c>, the
    /// ConfigBoundNET generator emits at build time:
    /// </para>
    /// <list type="bullet">
    ///   <item><description><c>DbConfig.SectionName</c> — a compile-time constant equal to <c>"Db"</c>.</description></item>
    ///   <item><description><c>DbConfig.Validator</c> — an <c>IValidateOptions&lt;DbConfig&gt;</c> that null-checks non-nullable properties.</description></item>
    ///   <item><description><c>DbConfigServiceCollectionExtensions.AddDbConfig</c> — the DI helper called in <c>Program.cs</c>.</description></item>
    /// </list>
    /// <para>
    /// Non-nullable reference-type properties (like <see cref="Conn"/>) are
    /// treated as required. Making a property nullable (e.g. <c>string?</c>)
    /// opts it out of validation.
    /// </para>
    /// </remarks>
    [ConfigSection("Db")]
    internal partial record DbConfig
    {
        /// <summary>The database connection string. Required.</summary>
        public string Conn { get; init; } = default!;

        /// <summary>Command timeout in seconds. Optional; defaults to 30.</summary>
        public int CommandTimeoutSeconds { get; init; } = 30;
    }
}
