// Copyright (c) ConfigBoundNET contributors. Licensed under the GPL-3 License.

using ConfigBoundNET.Example;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;

// ─────────────────────────────────────────────────────────────────────────────
// 1. Build a host using the standard Generic Host pattern.
//    CreateApplicationBuilder wires up appsettings.json, environment variables,
//    and command line arguments into builder.Configuration automatically.
// ─────────────────────────────────────────────────────────────────────────────
var builder = Host.CreateApplicationBuilder(args);

// ─────────────────────────────────────────────────────────────────────────────
// 2. Register the strongly-typed config with a single call. The extension
//    method AddDbConfig is generated by ConfigBoundNET from the [ConfigSection]
//    attribute on DbConfig below — it:
//
//      • binds the "Db" section to a DbConfig instance,
//      • registers the generated DbConfig.Validator (IValidateOptions<DbConfig>),
//      • and wires change-token propagation so IOptionsMonitor picks up reloads.
//
//    We chain ValidateOnStart() so missing values fail fast when the host
//    starts rather than on first IOptions<T> resolution.
// ─────────────────────────────────────────────────────────────────────────────
builder.Services
    .AddDbConfig(builder.Configuration)
    .AddOptions<DbConfig>()
    .ValidateOnStart();

using var app = builder.Build();

// ─────────────────────────────────────────────────────────────────────────────
// 3. Resolve the fully validated instance and use it.
// ─────────────────────────────────────────────────────────────────────────────
var dbConfig = app.Services.GetRequiredService<IOptions<DbConfig>>().Value;

System.Console.WriteLine($"[{DbConfig.SectionName}] Conn                   = {dbConfig.Conn}");
System.Console.WriteLine($"[{DbConfig.SectionName}] CommandTimeoutSeconds  = {dbConfig.CommandTimeoutSeconds}");
System.Console.WriteLine($"[{DbConfig.SectionName}] ReplicaConn            = {dbConfig.ReplicaConn ?? "(not set)"}");
System.Console.WriteLine();
System.Console.WriteLine("Validation passed — all cross-field rules satisfied.");

namespace ConfigBoundNET.Example
{
    /// <summary>
    /// Strongly-typed view of the <c>"Db"</c> configuration section.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Because this type is marked with <c>[ConfigSection("Db")]</c>, the
    /// ConfigBoundNET generator emits at build time:
    /// </para>
    /// <list type="bullet">
    ///   <item><description><c>DbConfig.SectionName</c> — a compile-time constant equal to <c>"Db"</c>.</description></item>
    ///   <item><description><c>DbConfig.Validator</c> — an <c>IValidateOptions&lt;DbConfig&gt;</c> that null-checks non-nullable properties and runs DataAnnotations checks.</description></item>
    ///   <item><description><c>DbConfigServiceCollectionExtensions.AddDbConfig</c> — the DI helper called in <c>Program.cs</c>.</description></item>
    ///   <item><description><c>partial void ValidateCustom</c> — a hook for cross-field validation rules that no single-property attribute can express.</description></item>
    /// </list>
    /// <para>
    /// Non-nullable reference-type properties (like <see cref="Conn"/>) are
    /// treated as required. Making a property nullable (e.g. <c>string?</c>)
    /// opts it out of validation.
    /// </para>
    /// </remarks>
    [ConfigSection("Db")]
    internal partial record DbConfig
    {
        /// <summary>The database connection string. Required.</summary>
        public string Conn { get; init; } = default!;

        /// <summary>Command timeout in seconds. Optional; defaults to 30.</summary>
        public int CommandTimeoutSeconds { get; init; } = 30;

        /// <summary>
        /// Optional replica connection string. When set, the timeout must be
        /// at least 5 seconds because replica failover adds latency.
        /// </summary>
        public string? ReplicaConn { get; init; }

        /// <summary>
        /// Cross-field validation: if a replica is configured, enforce a
        /// minimum timeout so connections don't fail during failover.
        /// This is the kind of rule that no single-property
        /// <c>[Range]</c> or <c>[Required]</c> attribute can express.
        /// </summary>
        partial void ValidateCustom(List<string> failures)
        {
            if (ReplicaConn is not null && CommandTimeoutSeconds < 5)
            {
                failures.Add(
                    $"[{SectionName}] When ReplicaConn is set, CommandTimeoutSeconds must be >= 5 " +
                    $"(got {CommandTimeoutSeconds}). Replica failover adds latency.");
            }
        }
    }
}
