// Copyright (c) ConfigBoundNET contributors. Licensed under the GPL-3 License.

namespace ConfigBoundNET;

/// <summary>
/// Embedded source for the <c>ConfigBoundNET.ConfigSectionAttribute</c> type.
/// The generator emits this verbatim via <see cref="Microsoft.CodeAnalysis.IncrementalGeneratorPostInitializationContext"/>
/// so that consumers need only a single package reference — they do not
/// have to ship a separate runtime library just to get the marker attribute.
/// </summary>
/// <remarks>
/// <para>
/// The attribute is declared <c>internal</c> so every compilation that uses the
/// generator gets its own private copy; this avoids the classic "two assemblies
/// both declare the same public attribute" collision.
/// </para>
/// <para>
/// It is also decorated with <c>[Conditional("CONFIGBOUNDNET_KEEP_ATTRIBUTES")]</c>.
/// Because <c>[Conditional]</c> propagates to attribute usages, the attribute
/// application is stripped from IL unless the consumer explicitly defines that
/// preprocessor symbol. The source generator still sees the attribute at build
/// time through the syntax tree, so build-time behaviour is unaffected.
/// </para>
/// </remarks>
internal static class AttributeSource
{
    /// <summary>The file name used when adding the attribute via AddSource.</summary>
    public const string HintName = "ConfigBoundNET.ConfigSectionAttribute.g.cs";

    /// <summary>The fully-qualified metadata name used by the generator's attribute lookup.</summary>
    public const string FullyQualifiedMetadataName = "ConfigBoundNET.ConfigSectionAttribute";

    /// <summary>The C# source text for the attribute type.</summary>
    public const string Source = @"// <auto-generated/>
#nullable enable

namespace ConfigBoundNET
{
    /// <summary>
    /// Marks a partial record or class as bound to a named configuration section.
    /// The ConfigBoundNET source generator picks up every type with this attribute
    /// and emits:
    /// <list type=""bullet"">
    ///   <item><description>An <c>IValidateOptions&lt;T&gt;</c> implementation named <c>Validator</c> nested inside the annotated type.</description></item>
    ///   <item><description>A <c>services.Add{TypeName}()</c> extension method that binds the section and wires the validator.</description></item>
    ///   <item><description>Build-time diagnostics for misuse (missing <c>partial</c>, empty section name, etc.).</description></item>
    /// </list>
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct,
        AllowMultiple = false,
        Inherited = false)]
    [global::System.Diagnostics.Conditional(""CONFIGBOUNDNET_KEEP_ATTRIBUTES"")]
    internal sealed class ConfigSectionAttribute : global::System.Attribute
    {
        /// <summary>Initializes a new instance of the <see cref=""ConfigSectionAttribute""/> class.</summary>
        /// <param name=""sectionName"">
        /// The configuration section name, e.g. <c>""Db""</c> for a section that lives
        /// at the top level of appsettings.json, or <c>""Services:Payments""</c> for
        /// a nested section.
        /// </param>
        public ConfigSectionAttribute(string sectionName)
        {
            SectionName = sectionName;
        }

        /// <summary>Gets the configuration section name supplied at construction time.</summary>
        public string SectionName { get; }
    }
}
";
}
