// Copyright (c) ConfigBoundNET contributors. Licensed under the GPL-3 License.

namespace ConfigBoundNET;

/// <summary>
/// Embedded source for the <c>ConfigBoundNET.ConfigSectionAttribute</c> type.
/// The generator emits this verbatim via <see cref="Microsoft.CodeAnalysis.IncrementalGeneratorPostInitializationContext"/>
/// so that consumers need only a single package reference — they do not
/// have to ship a separate runtime library just to get the marker attribute.
/// </summary>
/// <remarks>
/// <para>
/// The attribute is declared <c>internal</c> so every compilation that uses the
/// generator gets its own private copy; this avoids the classic "two assemblies
/// both declare the same public attribute" collision.
/// </para>
/// <para>
/// It is also decorated with <c>[Conditional("CONFIGBOUNDNET_KEEP_ATTRIBUTES")]</c>.
/// Because <c>[Conditional]</c> propagates to attribute usages, the attribute
/// application is stripped from IL unless the consumer explicitly defines that
/// preprocessor symbol. The source generator still sees the attribute at build
/// time through the syntax tree, so build-time behaviour is unaffected.
/// </para>
/// </remarks>
internal static class AttributeSource
{
    /// <summary>The file name used when adding the attribute via AddSource.</summary>
    public const string HintName = "ConfigBoundNET.ConfigSectionAttribute.g.cs";

    /// <summary>The file name used when adding the OptionsFactory helper via AddSource.</summary>
    public const string OptionsFactoryHintName = "ConfigBoundNET.ConfigBoundOptionsFactory.g.cs";

    /// <summary>The file name used when adding the <c>[Sensitive]</c> attribute via AddSource.</summary>
    public const string SensitiveAttributeHintName = "ConfigBoundNET.SensitiveAttribute.g.cs";

    /// <summary>The fully-qualified metadata name used by the generator's attribute lookup.</summary>
    public const string FullyQualifiedMetadataName = "ConfigBoundNET.ConfigSectionAttribute";

    /// <summary>
    /// Source for a tiny <c>IOptionsFactory&lt;T&gt;</c> shim that lets the
    /// generated DI extension method override how option instances are created
    /// without losing the standard configure/post-configure/validate pipeline.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The default <c>OptionsFactory&lt;T&gt;.CreateInstance</c> calls
    /// <c>Activator.CreateInstance&lt;T&gt;()</c>, which gives us a
    /// default-initialised options object. ConfigBoundNET needs to call its
    /// own generated constructor instead so it can populate
    /// <c>init</c>-only properties at construction time. We accomplish that
    /// by subclassing <c>OptionsFactory&lt;T&gt;</c> and overriding the
    /// protected virtual <c>CreateInstance</c> hook.
    /// </para>
    /// <para>
    /// Because the override is the only thing that differs per type, the
    /// subclass itself can be a single generic helper that takes a delegate.
    /// We emit it once per compilation as <c>internal</c> so multiple
    /// generator-using projects in the same solution don't collide.
    /// </para>
    /// </remarks>
    public const string OptionsFactorySource = @"// <auto-generated/>
#nullable enable

namespace ConfigBoundNET
{
    /// <summary>
    /// Generic <c>IOptionsFactory&lt;T&gt;</c> shim that lets ConfigBoundNET
    /// supply its own instance constructor while keeping the standard
    /// configure / post-configure / validate pipeline intact.
    /// </summary>
    /// <typeparam name=""T"">The options type.</typeparam>
    /// <remarks>
    /// The <c>[DynamicallyAccessedMembers]</c> annotation on <c>T</c>
    /// matches the one on the base <c>OptionsFactory&lt;TOptions&gt;</c>'s
    /// type parameter. Without it, the trim analyzer raises IL2091 at every
    /// generated registration site, since our generic parameter would be
    /// flowing into a stricter target.
    /// </remarks>
    internal sealed class ConfigBoundOptionsFactory<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T> : global::Microsoft.Extensions.Options.OptionsFactory<T>
        where T : class
    {
        private readonly global::System.Func<string, T> _instanceFactory;

        public ConfigBoundOptionsFactory(
            global::System.Collections.Generic.IEnumerable<global::Microsoft.Extensions.Options.IConfigureOptions<T>> setups,
            global::System.Collections.Generic.IEnumerable<global::Microsoft.Extensions.Options.IPostConfigureOptions<T>> postConfigures,
            global::System.Collections.Generic.IEnumerable<global::Microsoft.Extensions.Options.IValidateOptions<T>> validations,
            global::System.Func<string, T> instanceFactory)
            : base(setups, postConfigures, validations)
        {
            _instanceFactory = instanceFactory;
        }

        /// <summary>
        /// Construct the options instance via the supplied factory delegate
        /// instead of <c>Activator.CreateInstance&lt;T&gt;()</c>. The base
        /// <c>Create</c> still runs all <c>IConfigureOptions&lt;T&gt;</c>,
        /// <c>IPostConfigureOptions&lt;T&gt;</c>, and validation passes after
        /// this returns, so users can still layer behaviour on top —
        /// the only constraint is that any post-construction configure step
        /// cannot mutate <c>init</c>-only properties (a C# language rule, not
        /// a ConfigBoundNET limitation).
        /// </summary>
        protected override T CreateInstance(string name) => _instanceFactory(name);
    }
}
";

    /// <summary>The C# source text for the attribute type.</summary>
    public const string Source = @"// <auto-generated/>
#nullable enable

namespace ConfigBoundNET
{
    /// <summary>
    /// Marks a partial record or class as bound to a named configuration section.
    /// The ConfigBoundNET source generator picks up every type with this attribute
    /// and emits:
    /// <list type=""bullet"">
    ///   <item><description>An <c>IValidateOptions&lt;T&gt;</c> implementation named <c>Validator</c> nested inside the annotated type.</description></item>
    ///   <item><description>A <c>services.Add{TypeName}()</c> extension method that binds the section and wires the validator.</description></item>
    ///   <item><description>Build-time diagnostics for misuse (missing <c>partial</c>, empty section name, etc.).</description></item>
    /// </list>
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct,
        AllowMultiple = false,
        Inherited = false)]
    [global::System.Diagnostics.Conditional(""CONFIGBOUNDNET_KEEP_ATTRIBUTES"")]
    internal sealed class ConfigSectionAttribute : global::System.Attribute
    {
        /// <summary>
        /// Initializes a new instance with an inferred section name.
        /// The generator derives the name from the type name by stripping
        /// common suffixes (<c>Config</c>, <c>Options</c>, <c>Settings</c>,
        /// <c>Configuration</c>). E.g. <c>DbConfig</c> becomes <c>""Db""</c>.
        /// </summary>
        public ConfigSectionAttribute()
        {
            SectionName = string.Empty;
        }

        /// <summary>Initializes a new instance of the <see cref=""ConfigSectionAttribute""/> class.</summary>
        /// <param name=""sectionName"">
        /// The configuration section name, e.g. <c>""Db""</c> for a section that lives
        /// at the top level of appsettings.json, or <c>""Services:Payments""</c> for
        /// a nested section.
        /// </param>
        public ConfigSectionAttribute(string sectionName)
        {
            SectionName = sectionName;
        }

        /// <summary>Gets the configuration section name supplied at construction time, or empty if inferred.</summary>
        public string SectionName { get; }

        /// <summary>
        /// When <see langword=""true""/>, signals that this type exists only as a
        /// nested config (a property, collection element, or dictionary value of
        /// another <c>[ConfigSection]</c>). The assembly-wide
        /// <c>AddConfigBoundSections</c> extension then wraps its registration in
        /// a <c>.Exists()</c> gate so a missing root section doesn't spuriously
        /// fail startup validation. Default <see langword=""false""/>.
        /// </summary>
        /// <remarks>
        /// The generator also auto-detects nested use when one <c>[ConfigSection]</c>
        /// in the same compilation references another via a property, collection
        /// element, or dictionary value. Setting this flag is necessary only for
        /// types whose nested use lives in a <em>different</em> assembly (a library
        /// author shipping nested-only building blocks to consumers), where the
        /// generator compiling the library can't see the downstream reference.
        /// </remarks>
        public bool IsNestedOnly { get; init; }
    }
}
";

    /// <summary>
    /// The C# source text for the <c>[Sensitive]</c> attribute. Applied to
    /// properties on a <c>[ConfigSection]</c>-annotated type, it causes the
    /// generator to redact the property's value in the emitted
    /// <c>ToString()</c> / <c>PrintMembers()</c> override so that secrets
    /// like connection strings and API keys don't leak into logs.
    /// </summary>
    /// <remarks>
    /// Same embedding pattern as <c>ConfigSectionAttribute</c>: <c>internal</c>
    /// so each compilation gets its own copy, and <c>[Conditional]</c>-stripped
    /// from IL unless the consumer explicitly defines
    /// <c>CONFIGBOUNDNET_KEEP_ATTRIBUTES</c>. The generator sees the attribute
    /// through the syntax tree at compile time; no runtime metadata is
    /// required.
    /// </remarks>
    public const string SensitiveAttributeSource = @"// <auto-generated/>
#nullable enable

namespace ConfigBoundNET
{
    /// <summary>
    /// Marks a property on a <c>[ConfigSection]</c>-annotated type as holding
    /// a secret (connection string, API key, access token, etc.). The
    /// ConfigBoundNET source generator emits a <c>ToString()</c> /
    /// <c>PrintMembers()</c> override that replaces the value with
    /// <c>""***""</c> so secrets do not leak through record-default logging
    /// or explicit <c>config.ToString()</c> calls.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null-valued sensitive properties still render as <c>null</c>, so
    /// missing-config is distinguishable from set-but-redacted at debug time.
    /// </para>
    /// <para>
    /// Scope: affects <c>ToString()</c> only. Structured-logging
    /// destructurers (Serilog <c>{@X}</c>, NLog <c>${object}</c>, etc.)
    /// reach past <c>ToString()</c> via reflection; configure your logger's
    /// type policy separately for those paths.
    /// </para>
    /// </remarks>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Property,
        AllowMultiple = false,
        Inherited = false)]
    [global::System.Diagnostics.Conditional(""CONFIGBOUNDNET_KEEP_ATTRIBUTES"")]
    internal sealed class SensitiveAttribute : global::System.Attribute
    {
    }
}
";
}
