// Copyright (c) ConfigBoundNET contributors. Licensed under the GPL-3 License.

using System.CodeDom.Compiler;
using System.IO;
using System.Text;

namespace ConfigBoundNET;

/// <summary>
/// Renders a <see cref="ConfigSectionModel"/> to C# source text.
/// </summary>
/// <remarks>
/// <para>
/// The emitter is a pure function of its input. It must not read anything from
/// the compilation or from disk — all state required to produce identical
/// output for identical input lives on <see cref="ConfigSectionModel"/>.
/// </para>
/// <para>
/// The generated code uses fully qualified type names (or explicit <c>using</c>
/// directives scoped to the generated file) to avoid colliding with any type
/// declared in user code.
/// </para>
/// </remarks>
internal static class SourceEmitter
{
    /// <summary>
    /// Produce the C# source for the validator and DI extension for a single
    /// <c>[ConfigSection]</c>-annotated type.
    /// </summary>
    public static string Emit(ConfigSectionModel model)
    {
        var buffer = new StringBuilder();
        using var stringWriter = new StringWriter(buffer);
        using var writer = new IndentedTextWriter(stringWriter, "    ");

        WriteHeader(writer);

        var hasNamespace = model.Namespace is not null;

        if (hasNamespace)
        {
            // File-scoped namespace is supported everywhere C# 10+ targets do.
            // We emit a file-scoped namespace so indentation stays sane.
            writer.Write("namespace ");
            writer.Write(model.Namespace);
            writer.WriteLine(";");
            writer.WriteLine();
        }

        WritePartialTypeWithValidator(writer, model);
        writer.WriteLine();
        WriteServiceCollectionExtensions(writer, model);

        writer.Flush();
        return buffer.ToString();
    }

    /// <summary>Writes the file header, auto-generated comment, and using directives.</summary>
    private static void WriteHeader(IndentedTextWriter writer)
    {
        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("//     This file was generated by ConfigBoundNET.");
        writer.WriteLine("//     Changes to this file will be lost when the generator re-runs.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine("#nullable enable");

        // Suppress noisy warnings inside generated code: unused fields, missing
        // docs, etc. We don't want user builds to fail on generator output.
        writer.WriteLine("#pragma warning disable CS1591");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes the partial record / class declaration that adds the
    /// <c>SectionName</c> constant and nested <c>Validator</c> class.
    /// </summary>
    private static void WritePartialTypeWithValidator(IndentedTextWriter writer, ConfigSectionModel model)
    {
        var typeKeyword = model.Kind == ConfigTypeKind.Record ? "partial record" : "partial class";

        writer.Write(typeKeyword);
        writer.Write(' ');
        writer.WriteLine(model.TypeName);
        writer.WriteLine("{");
        writer.Indent++;

        // ── Section-name constant. Exposed publicly so users can reference it
        //    elsewhere (logging, telemetry, tests) without stringly-typing.
        writer.WriteLine("/// <summary>");
        writer.Write("/// The configuration section name declared via <c>[ConfigSection(\"");
        writer.Write(Escape(model.SectionName));
        writer.WriteLine("\")]</c>.");
        writer.WriteLine("/// </summary>");
        writer.Write("public const string SectionName = \"");
        writer.Write(Escape(model.SectionName));
        writer.WriteLine("\";");
        writer.WriteLine();

        // ── Nested Validator class implementing IValidateOptions<T>.
        writer.WriteLine("/// <summary>");
        writer.Write("/// Auto-generated validator for <see cref=\"");
        writer.Write(model.TypeName);
        writer.WriteLine("\"/>.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <remarks>");
        writer.WriteLine("/// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly");
        writer.WriteLine("/// at startup if <c>ValidateOnStart()</c> is chained on the options builder.");
        writer.WriteLine("/// </remarks>");

        writer.Write("public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<");
        writer.Write(model.TypeName);
        writer.WriteLine(">");
        writer.WriteLine("{");
        writer.Indent++;

        writer.Write("public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, ");
        writer.Write(model.TypeName);
        writer.WriteLine(" options)");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("if (options is null)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(\"");
        writer.Write(model.TypeName);
        writer.WriteLine(" instance was null.\");");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("var failures = new global::System.Collections.Generic.List<string>();");
        writer.WriteLine();

        // ── Null / whitespace checks for every required property.
        foreach (var prop in model.Properties)
        {
            if (!prop.IsRequired)
            {
                continue;
            }

            if (prop.IsString)
            {
                // Strings get a stricter check: whitespace-only config values
                // are almost always a deployment mistake.
                writer.Write("if (string.IsNullOrWhiteSpace(options.");
                writer.Write(prop.Name);
                writer.WriteLine("))");
                writer.WriteLine("{");
                writer.Indent++;
                writer.Write("failures.Add(\"[");
                writer.Write(Escape(model.SectionName));
                writer.Write(':');
                writer.Write(prop.Name);
                writer.WriteLine("] is required but was null, empty, or whitespace.\");");
                writer.Indent--;
                writer.WriteLine("}");
            }
            else if (prop.IsReferenceType)
            {
                writer.Write("if (options.");
                writer.Write(prop.Name);
                writer.WriteLine(" is null)");
                writer.WriteLine("{");
                writer.Indent++;
                writer.Write("failures.Add(\"[");
                writer.Write(Escape(model.SectionName));
                writer.Write(':');
                writer.Write(prop.Name);
                writer.WriteLine("] is required but was null.\");");
                writer.Indent--;
                writer.WriteLine("}");
            }
            // Value types: no runtime null check; the binder supplies defaults.
            // DataAnnotations or custom validators can layer additional rules.
        }

        writer.WriteLine();
        writer.WriteLine("return failures.Count > 0");
        writer.Indent++;
        writer.WriteLine("? global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures)");
        writer.WriteLine(": global::Microsoft.Extensions.Options.ValidateOptionsResult.Success;");
        writer.Indent--;

        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes the DI extension class containing <c>Add{TypeName}</c>.
    /// </summary>
    /// <remarks>
    /// The class is declared at namespace scope (same namespace as the type
    /// itself) so that <c>using</c>-ing the target type's namespace brings the
    /// extension method into scope automatically.
    /// </remarks>
    private static void WriteServiceCollectionExtensions(IndentedTextWriter writer, ConfigSectionModel model)
    {
        writer.WriteLine("/// <summary>");
        writer.Write("/// Dependency-injection helpers for <see cref=\"");
        writer.Write(model.TypeName);
        writer.WriteLine("\"/>.");
        writer.WriteLine("/// </summary>");

        writer.Write("public static class ");
        writer.Write(model.TypeName);
        writer.WriteLine("ServiceCollectionExtensions");
        writer.WriteLine("{");
        writer.Indent++;

        // ── XML docs on the extension method.
        writer.WriteLine("/// <summary>");
        writer.Write("/// Binds <see cref=\"");
        writer.Write(model.TypeName);
        writer.Write("\"/> to the <c>\"");
        writer.Write(Escape(model.SectionName));
        writer.WriteLine("\"</c> configuration section and registers the generated validator.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"services\">The service collection to register into.</param>");
        writer.WriteLine("/// <param name=\"configuration\">The application's <c>IConfiguration</c> root or parent section.</param>");
        writer.WriteLine("/// <returns>");
        writer.WriteLine("/// The original <paramref name=\"services\"/> instance, enabling fluent chaining.");
        writer.WriteLine("/// </returns>");
        writer.WriteLine("/// <exception cref=\"global::System.ArgumentNullException\">Thrown when <paramref name=\"services\"/> or <paramref name=\"configuration\"/> is <see langword=\"null\"/>.</exception>");

        writer.Write("public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add");
        writer.Write(model.TypeName);
        writer.WriteLine("(");
        writer.Indent++;
        writer.WriteLine("this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        writer.WriteLine("global::Microsoft.Extensions.Configuration.IConfiguration configuration)");
        writer.Indent--;

        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("if (services is null) throw new global::System.ArgumentNullException(nameof(services));");
        writer.WriteLine("if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));");
        writer.WriteLine();

        // ── Register the generated validator idempotently. TryAddEnumerable
        //    prevents duplicate Validator registrations if the user calls
        //    Add{TypeName}() more than once.
        writer.Write("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(");
        writer.WriteLine();
        writer.Indent++;
        writer.WriteLine("services,");
        writer.Write("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<");
        writer.Write(model.TypeName);
        writer.Write(">, ");
        writer.Write(model.TypeName);
        writer.WriteLine(".Validator>());");
        writer.Indent--;
        writer.WriteLine();

        // ── Bind the section. We use the Microsoft.Extensions.Options.ConfigurationExtensions
        //    package's Configure<T>(IConfiguration) overload, which internally wires up
        //    both IConfigureOptions<T> and IOptionsChangeTokenSource<T> (so the options
        //    update when configuration reloads).
        writer.Write("global::Microsoft.Extensions.DependencyInjection.OptionsConfigurationServiceCollectionExtensions.Configure<");
        writer.Write(model.TypeName);
        writer.WriteLine(">(");
        writer.Indent++;
        writer.WriteLine("services,");
        writer.Write("configuration.GetSection(");
        writer.Write(model.TypeName);
        writer.WriteLine(".SectionName));");
        writer.Indent--;
        writer.WriteLine();

        writer.WriteLine("return services;");

        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Escapes a string for safe inclusion inside a C# double-quoted literal.
    /// </summary>
    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
