// Copyright (c) ConfigBoundNET contributors. Licensed under the GPL-3 License.

using System.CodeDom.Compiler;
using System.IO;
using System.Text;

namespace ConfigBoundNET;

/// <summary>
/// Renders a <see cref="ConfigSectionModel"/> to C# source text.
/// </summary>
/// <remarks>
/// <para>
/// The emitter is a pure function of its input. It must not read anything from
/// the compilation or from disk — all state required to produce identical
/// output for identical input lives on <see cref="ConfigSectionModel"/>.
/// </para>
/// <para>
/// The generated code uses fully qualified type names (or explicit <c>using</c>
/// directives scoped to the generated file) to avoid colliding with any type
/// declared in user code.
/// </para>
/// </remarks>
internal static class SourceEmitter
{
    /// <summary>
    /// Produce the C# source for the validator and DI extension for a single
    /// <c>[ConfigSection]</c>-annotated type.
    /// </summary>
    public static string Emit(ConfigSectionModel model)
    {
        var buffer = new StringBuilder();
        using var stringWriter = new StringWriter(buffer);
        using var writer = new IndentedTextWriter(stringWriter, "    ");

        WriteHeader(writer);

        var hasNamespace = model.Namespace is not null;

        if (hasNamespace)
        {
            // File-scoped namespace is supported everywhere C# 10+ targets do.
            // We emit a file-scoped namespace so indentation stays sane.
            writer.Write("namespace ");
            writer.Write(model.Namespace);
            writer.WriteLine(";");
            writer.WriteLine();
        }

        WritePartialTypeWithValidator(writer, model);
        writer.WriteLine();
        WriteServiceCollectionExtensions(writer, model);

        writer.Flush();
        return buffer.ToString();
    }

    /// <summary>Writes the file header, auto-generated comment, and using directives.</summary>
    private static void WriteHeader(IndentedTextWriter writer)
    {
        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("//     This file was generated by ConfigBoundNET.");
        writer.WriteLine("//     Changes to this file will be lost when the generator re-runs.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine("#nullable enable");

        // Suppress noisy warnings inside generated code: unused fields, missing
        // docs, etc. We don't want user builds to fail on generator output.
        writer.WriteLine("#pragma warning disable CS1591");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes the partial record / class declaration that adds the
    /// <c>SectionName</c> constant, the static reflection-free <c>Bind</c>
    /// helper, and the nested <c>Validator</c> class.
    /// </summary>
    private static void WritePartialTypeWithValidator(IndentedTextWriter writer, ConfigSectionModel model)
    {
        var typeKeyword = model.Kind == ConfigTypeKind.Record ? "partial record" : "partial class";

        writer.Write(typeKeyword);
        writer.Write(' ');
        writer.WriteLine(model.TypeName);
        writer.WriteLine("{");
        writer.Indent++;

        // ── Section-name constant. Exposed publicly so users can reference it
        //    elsewhere (logging, telemetry, tests) without stringly-typing.
        writer.WriteLine("/// <summary>");
        writer.Write("/// The configuration section name declared via <c>[ConfigSection(\"");
        writer.Write(Escape(model.SectionName));
        writer.WriteLine("\")]</c>.");
        writer.WriteLine("/// </summary>");
        writer.Write("public const string SectionName = \"");
        writer.Write(Escape(model.SectionName));
        writer.WriteLine("\";");
        writer.WriteLine();

        // ── Static Bind method: AOT-safe, reflection-free configuration binder.
        //    Lives inside the partial type so it can write to init-only and
        //    private setters without going through reflection.
        WriteBindMethod(writer, model);
        writer.WriteLine();

        // ── Nested Validator class implementing IValidateOptions<T>.
        writer.WriteLine("/// <summary>");
        writer.Write("/// Auto-generated validator for <see cref=\"");
        writer.Write(model.TypeName);
        writer.WriteLine("\"/>.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <remarks>");
        writer.WriteLine("/// Invoked lazily on first <c>IOptions&lt;T&gt;</c> resolution, or eagerly");
        writer.WriteLine("/// at startup if <c>ValidateOnStart()</c> is chained on the options builder.");
        writer.WriteLine("/// </remarks>");

        writer.Write("public sealed class Validator : global::Microsoft.Extensions.Options.IValidateOptions<");
        writer.Write(model.TypeName);
        writer.WriteLine(">");
        writer.WriteLine("{");
        writer.Indent++;

        // ── Emit precompiled Regex fields for [RegularExpression] and
        //    [EmailAddress] annotations. Declared as static readonly so the
        //    regex is compiled once, not on every Validate call.
        WriteRegexFields(writer, model);

        writer.Write("public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(string? name, ");
        writer.Write(model.TypeName);
        writer.WriteLine(" options)");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("if (options is null)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(\"");
        writer.Write(model.TypeName);
        writer.WriteLine(" instance was null.\");");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("var failures = new global::System.Collections.Generic.List<string>();");
        writer.WriteLine();

        // ── Null / whitespace checks for every required property.
        foreach (var prop in model.Properties)
        {
            if (!prop.IsRequired)
            {
                continue;
            }

            if (prop.IsString)
            {
                // Strings get a stricter check: whitespace-only config values
                // are almost always a deployment mistake.
                writer.Write("if (string.IsNullOrWhiteSpace(options.");
                writer.Write(prop.Name);
                writer.WriteLine("))");
                writer.WriteLine("{");
                writer.Indent++;
                writer.Write("failures.Add(\"[");
                writer.Write(Escape(model.SectionName));
                writer.Write(':');
                writer.Write(prop.Name);
                writer.WriteLine("] is required but was null, empty, or whitespace.\");");
                writer.Indent--;
                writer.WriteLine("}");
            }
            else if (prop.IsReferenceType)
            {
                writer.Write("if (options.");
                writer.Write(prop.Name);
                writer.WriteLine(" is null)");
                writer.WriteLine("{");
                writer.Indent++;
                writer.Write("failures.Add(\"[");
                writer.Write(Escape(model.SectionName));
                writer.Write(':');
                writer.Write(prop.Name);
                writer.WriteLine("] is required but was null.\");");
                writer.Indent--;
                writer.WriteLine("}");
            }
            // Value types: no runtime null check; the binder supplies defaults.
            // DataAnnotations validation provides value-type checks below.
        }

        // ── DataAnnotations checks, emitted after the null/whitespace pass
        //    so the user sees the "required" error first when a value is
        //    missing, and the annotation checks (all null-guarded for strings)
        //    don't add NRE noise.
        foreach (var prop in model.Properties)
        {
            foreach (var ann in prop.DataAnnotations)
            {
                WriteAnnotationCheck(writer, model, prop, ann);
            }
        }

        writer.WriteLine();
        writer.WriteLine("return failures.Count > 0");
        writer.Indent++;
        writer.WriteLine("? global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures)");
        writer.WriteLine(": global::Microsoft.Extensions.Options.ValidateOptionsResult.Success;");
        writer.Indent--;

        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes the DI extension class containing <c>Add{TypeName}</c>.
    /// </summary>
    /// <remarks>
    /// The class is declared at namespace scope (same namespace as the type
    /// itself) so that <c>using</c>-ing the target type's namespace brings the
    /// extension method into scope automatically.
    /// </remarks>
    private static void WriteServiceCollectionExtensions(IndentedTextWriter writer, ConfigSectionModel model)
    {
        writer.WriteLine("/// <summary>");
        writer.Write("/// Dependency-injection helpers for <see cref=\"");
        writer.Write(model.TypeName);
        writer.WriteLine("\"/>.");
        writer.WriteLine("/// </summary>");

        writer.Write("public static class ");
        writer.Write(model.TypeName);
        writer.WriteLine("ServiceCollectionExtensions");
        writer.WriteLine("{");
        writer.Indent++;

        // ── XML docs on the extension method.
        writer.WriteLine("/// <summary>");
        writer.Write("/// Binds <see cref=\"");
        writer.Write(model.TypeName);
        writer.Write("\"/> to the <c>\"");
        writer.Write(Escape(model.SectionName));
        writer.WriteLine("\"</c> configuration section and registers the generated validator.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"services\">The service collection to register into.</param>");
        writer.WriteLine("/// <param name=\"configuration\">The application's <c>IConfiguration</c> root or parent section.</param>");
        writer.WriteLine("/// <returns>");
        writer.WriteLine("/// The original <paramref name=\"services\"/> instance, enabling fluent chaining.");
        writer.WriteLine("/// </returns>");
        writer.WriteLine("/// <exception cref=\"global::System.ArgumentNullException\">Thrown when <paramref name=\"services\"/> or <paramref name=\"configuration\"/> is <see langword=\"null\"/>.</exception>");

        writer.Write("public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add");
        writer.Write(model.TypeName);
        writer.WriteLine("(");
        writer.Indent++;
        writer.WriteLine("this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        writer.WriteLine("global::Microsoft.Extensions.Configuration.IConfiguration configuration)");
        writer.Indent--;

        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("if (services is null) throw new global::System.ArgumentNullException(nameof(services));");
        writer.WriteLine("if (configuration is null) throw new global::System.ArgumentNullException(nameof(configuration));");
        writer.WriteLine();

        // ── Capture the target section once so the closures below all share
        //    the same live reference. Each property read through `section` is
        //    live, which is what makes IOptionsMonitor reload-on-change work.
        writer.Write("var section = configuration.GetSection(");
        writer.Write(model.TypeName);
        writer.WriteLine(".SectionName);");
        writer.WriteLine();

        // ── Make sure the core Options infrastructure is registered. AddOptions()
        //    is idempotent, so this is safe regardless of call order.
        writer.WriteLine("global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);");
        writer.WriteLine();

        // ── Register the generated validator idempotently. TryAddEnumerable
        //    prevents duplicate Validator registrations if the user calls
        //    Add{TypeName}() more than once.
        writer.Write("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(");
        writer.WriteLine();
        writer.Indent++;
        writer.WriteLine("services,");
        writer.Write("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IValidateOptions<");
        writer.Write(model.TypeName);
        writer.Write(">, ");
        writer.Write(model.TypeName);
        writer.WriteLine(".Validator>());");
        writer.Indent--;
        writer.WriteLine();

        // ── Replace the default OptionsFactory<T> with our shim. The shim
        //    overrides CreateInstance to call the generated constructor —
        //    that's the only AOT-safe way to populate `init`-only properties
        //    without going through ConfigurationBinder + reflection. The base
        //    OptionsFactory<T> still runs every IConfigureOptions / IPostConfigureOptions
        //    / IValidateOptions registered against the type, so users can layer
        //    behaviour on top normally (with the caveat that those callbacks
        //    cannot mutate `init`-only properties — a C# language rule).
        writer.Write("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(");
        writer.WriteLine();
        writer.Indent++;
        writer.WriteLine("services,");
        writer.Write("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsFactory<");
        writer.Write(model.TypeName);
        writer.WriteLine(">>(sp =>");
        writer.Indent++;
        writer.Write("new global::ConfigBoundNET.ConfigBoundOptionsFactory<");
        writer.Write(model.TypeName);
        writer.WriteLine(">(");
        writer.Indent++;
        writer.Write("global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IConfigureOptions<");
        writer.Write(model.TypeName);
        writer.WriteLine(">>(sp),");
        writer.Write("global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IPostConfigureOptions<");
        writer.Write(model.TypeName);
        writer.WriteLine(">>(sp),");
        writer.Write("global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Options.IValidateOptions<");
        writer.Write(model.TypeName);
        writer.WriteLine(">>(sp),");
        writer.Write("_ => new ");
        writer.Write(model.TypeName);
        writer.WriteLine("(section))));");
        writer.Indent--;
        writer.Indent--;
        writer.Indent--;
        writer.WriteLine();

        // ── Hot-reload support: forwarding the section's change token into
        //    the Options framework is what makes IOptionsMonitor<T> react to
        //    file edits or other IConfigurationProvider reloads. This is the
        //    same registration the legacy Configure<T>(IConfiguration) made
        //    under the hood — we just keep it instead of relying on it.
        writer.Write("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(");
        writer.WriteLine();
        writer.Indent++;
        writer.WriteLine("services,");
        writer.Write("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<");
        writer.Write(model.TypeName);
        writer.WriteLine(">>(");
        writer.Indent++;
        writer.Write("new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<");
        writer.Write(model.TypeName);
        writer.WriteLine(">(");
        writer.Indent++;
        writer.WriteLine("global::Microsoft.Extensions.Options.Options.DefaultName,");
        writer.WriteLine("section)));");
        writer.Indent--;
        writer.Indent--;
        writer.Indent--;
        writer.WriteLine();

        writer.WriteLine("return services;");

        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes a constructor overload that builds the options instance directly
    /// from an <c>IConfigurationSection</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is the heart of the AOT-safe path. By emitting one explicit
    /// assignment per property — rather than calling
    /// <c>ConfigurationBinder.Bind</c> — we eliminate every reflection and
    /// runtime-codegen call from the binding pipeline. The resulting code is
    /// fully trim- and Native-AOT-friendly.
    /// </para>
    /// <para>
    /// We emit a <em>constructor</em> rather than a static method because C#
    /// only permits writes to <c>init</c>-only properties from object
    /// initializers, instance constructors, and other <c>init</c> accessors.
    /// A static method on the same type would not qualify, so the constructor
    /// approach is the only AOT-friendly way to populate <c>init</c>-only
    /// records.
    /// </para>
    /// <para>
    /// The constructor deliberately does <em>not</em> chain to <c>: this()</c>.
    /// Declaring an explicit constructor on a record suppresses the compiler's
    /// auto-generated parameterless constructor, so a <c>: this()</c> chain
    /// would reference a constructor that no longer exists. Field initializers
    /// (<c>= 30</c>, etc.) still run as the prologue of any constructor that
    /// has no <c>: this(...)</c> chain, so user-supplied defaults survive
    /// without needing the chain.
    /// </para>
    /// </remarks>
    private static void WriteBindMethod(IndentedTextWriter writer, ConfigSectionModel model)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Reflection-free constructor generated by ConfigBoundNET.");
        writer.WriteLine("/// Reads values from the supplied configuration section and copies");
        writer.WriteLine("/// them into a new instance, preserving any field-initializer defaults");
        writer.WriteLine("/// for keys that are absent from the section.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"section\">The configuration section to read from.</param>");

        writer.Write("public ");
        writer.Write(model.TypeName);
        writer.WriteLine("(global::Microsoft.Extensions.Configuration.IConfigurationSection section)");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("if (section is null) throw new global::System.ArgumentNullException(nameof(section));");

        if (model.Properties.Length > 0)
        {
            writer.WriteLine();
        }

        foreach (var prop in model.Properties)
        {
            WriteBindAssignment(writer, prop);
        }

        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Emits the per-property assignment block inside <c>Bind</c> for a single
    /// <see cref="ConfigPropertyModel"/>, dispatching on its
    /// <see cref="BindingStrategy"/>.
    /// </summary>
    /// <remarks>
    /// All branches share the same shape:
    /// <list type="number">
    ///   <item><description>Read the raw string (or sub-section) from configuration.</description></item>
    ///   <item><description>If absent, leave the property at whatever default the user declared.</description></item>
    ///   <item><description>If present, parse it with the appropriate culture-invariant
    ///   <c>TryParse</c>; on failure, leave the property alone (validation
    ///   will fail later if it was required).</description></item>
    /// </list>
    /// </remarks>
    private static void WriteBindAssignment(IndentedTextWriter writer, ConfigPropertyModel prop)
    {
        switch (prop.Binding)
        {
            case BindingStrategy.Unsupported:
                // CB0010 was already raised in the model builder; emit a comment
                // so the generated source explains the gap to anyone reading it.
                writer.Write("// Skipped property '");
                writer.Write(prop.Name);
                writer.WriteLine("' (CB0010): type is not bindable by ConfigBoundNET.");
                return;

            case BindingStrategy.String:
                EmitStringAssignment(writer, prop);
                return;

            case BindingStrategy.Boolean:
            case BindingStrategy.Integer:
            case BindingStrategy.FloatingPoint:
                EmitPrimitiveTryParse(writer, prop);
                return;

            case BindingStrategy.Guid:
                EmitTryParseInvariant(writer, prop, "global::System.Guid");
                return;

            case BindingStrategy.TimeSpan:
                EmitTryParseInvariant(writer, prop, "global::System.TimeSpan");
                return;

            case BindingStrategy.DateTime:
                EmitDateTimeAssignment(writer, prop, "global::System.DateTime");
                return;

            case BindingStrategy.DateTimeOffset:
                EmitDateTimeAssignment(writer, prop, "global::System.DateTimeOffset");
                return;

            case BindingStrategy.Uri:
                EmitUriAssignment(writer, prop);
                return;

            case BindingStrategy.Enum:
                EmitEnumAssignment(writer, prop);
                return;

            case BindingStrategy.NestedConfig:
                EmitNestedAssignment(writer, prop);
                return;
        }
    }

    /// <summary>String: copy the raw value verbatim if present.</summary>
    private static void EmitStringAssignment(IndentedTextWriter writer, ConfigPropertyModel prop)
    {
        var raw = LocalName(prop.Name, "Raw");

        writer.Write("var ");
        writer.Write(raw);
        writer.Write(" = section[\"");
        writer.Write(prop.Name);
        writer.WriteLine("\"];");

        writer.Write("if (");
        writer.Write(raw);
        writer.WriteLine(" is not null)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("this.");
        writer.Write(prop.Name);
        writer.Write(" = ");
        writer.Write(raw);
        writer.WriteLine(";");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Primitive types whose <c>TryParse</c> overload accepts an
    /// <see cref="System.Globalization.NumberStyles"/> + <see cref="System.IFormatProvider"/>
    /// pair (or, in the case of <c>bool</c>, no extra arguments).
    /// </summary>
    private static void EmitPrimitiveTryParse(IndentedTextWriter writer, ConfigPropertyModel prop)
    {
        var keyword = prop.ParseTypeKeyword!;
        var raw = LocalName(prop.Name, "Raw");
        var parsed = LocalName(prop.Name, "Parsed");

        writer.Write("var ");
        writer.Write(raw);
        writer.Write(" = section[\"");
        writer.Write(prop.Name);
        writer.WriteLine("\"];");

        if (prop.Binding == BindingStrategy.Boolean)
        {
            // bool.TryParse takes (string, out bool) only.
            writer.Write("if (");
            writer.Write(raw);
            writer.Write(" is not null && bool.TryParse(");
            writer.Write(raw);
            writer.Write(", out var ");
            writer.Write(parsed);
            writer.WriteLine("))");
        }
        else
        {
            // Numeric: always parse with the invariant culture so config files
            // are portable across locales.
            var styles = prop.Binding == BindingStrategy.Integer
                ? "global::System.Globalization.NumberStyles.Integer"
                : "global::System.Globalization.NumberStyles.Float";

            writer.Write("if (");
            writer.Write(raw);
            writer.Write(" is not null && ");
            writer.Write(keyword);
            writer.Write(".TryParse(");
            writer.Write(raw);
            writer.Write(", ");
            writer.Write(styles);
            writer.Write(", global::System.Globalization.CultureInfo.InvariantCulture, out var ");
            writer.Write(parsed);
            writer.WriteLine("))");
        }

        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("this.");
        writer.Write(prop.Name);
        writer.Write(" = ");
        writer.Write(parsed);
        writer.WriteLine(";");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Guid / TimeSpan: invariant-culture <c>TryParse</c>.</summary>
    private static void EmitTryParseInvariant(IndentedTextWriter writer, ConfigPropertyModel prop, string fullyQualifiedType)
    {
        var raw = LocalName(prop.Name, "Raw");
        var parsed = LocalName(prop.Name, "Parsed");

        writer.Write("var ");
        writer.Write(raw);
        writer.Write(" = section[\"");
        writer.Write(prop.Name);
        writer.WriteLine("\"];");

        writer.Write("if (");
        writer.Write(raw);
        writer.Write(" is not null && ");
        writer.Write(fullyQualifiedType);
        writer.Write(".TryParse(");
        writer.Write(raw);
        writer.Write(", global::System.Globalization.CultureInfo.InvariantCulture, out var ");
        writer.Write(parsed);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("this.");
        writer.Write(prop.Name);
        writer.Write(" = ");
        writer.Write(parsed);
        writer.WriteLine(";");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>DateTime / DateTimeOffset: invariant culture + roundtrip kind.</summary>
    private static void EmitDateTimeAssignment(IndentedTextWriter writer, ConfigPropertyModel prop, string fullyQualifiedType)
    {
        var raw = LocalName(prop.Name, "Raw");
        var parsed = LocalName(prop.Name, "Parsed");

        writer.Write("var ");
        writer.Write(raw);
        writer.Write(" = section[\"");
        writer.Write(prop.Name);
        writer.WriteLine("\"];");

        writer.Write("if (");
        writer.Write(raw);
        writer.Write(" is not null && ");
        writer.Write(fullyQualifiedType);
        writer.Write(".TryParse(");
        writer.Write(raw);
        writer.Write(", global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.RoundtripKind, out var ");
        writer.Write(parsed);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("this.");
        writer.Write(prop.Name);
        writer.Write(" = ");
        writer.Write(parsed);
        writer.WriteLine(";");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Uri: <c>Uri.TryCreate</c> with <c>UriKind.Absolute</c>.</summary>
    private static void EmitUriAssignment(IndentedTextWriter writer, ConfigPropertyModel prop)
    {
        var raw = LocalName(prop.Name, "Raw");
        var parsed = LocalName(prop.Name, "Parsed");

        writer.Write("var ");
        writer.Write(raw);
        writer.Write(" = section[\"");
        writer.Write(prop.Name);
        writer.WriteLine("\"];");

        writer.Write("if (");
        writer.Write(raw);
        writer.Write(" is not null && global::System.Uri.TryCreate(");
        writer.Write(raw);
        writer.Write(", global::System.UriKind.Absolute, out var ");
        writer.Write(parsed);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("this.");
        writer.Write(prop.Name);
        writer.Write(" = ");
        writer.Write(parsed);
        writer.WriteLine(";");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Enums: <c>Enum.TryParse&lt;T&gt;</c> is annotated AOT-safe by the BCL.</summary>
    private static void EmitEnumAssignment(IndentedTextWriter writer, ConfigPropertyModel prop)
    {
        var raw = LocalName(prop.Name, "Raw");
        var parsed = LocalName(prop.Name, "Parsed");
        var enumType = prop.EnumFullyQualifiedName!;

        writer.Write("var ");
        writer.Write(raw);
        writer.Write(" = section[\"");
        writer.Write(prop.Name);
        writer.WriteLine("\"];");

        writer.Write("if (");
        writer.Write(raw);
        writer.Write(" is not null && global::System.Enum.TryParse<");
        writer.Write(enumType);
        writer.Write(">(");
        writer.Write(raw);
        writer.Write(", ignoreCase: true, out var ");
        writer.Write(parsed);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("this.");
        writer.Write(prop.Name);
        writer.Write(" = ");
        writer.Write(parsed);
        writer.WriteLine(";");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Nested config types: invoke the inner type's generated
    /// <c>(IConfigurationSection)</c> constructor. The inner type is
    /// guaranteed to have one because the classifier only returns
    /// <see cref="BindingStrategy.NestedConfig"/> when the type is itself
    /// <c>[ConfigSection]</c>-annotated.
    /// </summary>
    private static void EmitNestedAssignment(IndentedTextWriter writer, ConfigPropertyModel prop)
    {
        var subsection = LocalName(prop.Name, "Section");
        var nestedType = prop.NestedTypeFullyQualifiedName!;

        writer.Write("var ");
        writer.Write(subsection);
        writer.Write(" = section.GetSection(\"");
        writer.Write(prop.Name);
        writer.WriteLine("\");");

        writer.Write("if (global::Microsoft.Extensions.Configuration.ConfigurationExtensions.Exists(");
        writer.Write(subsection);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        // We're in a constructor, so writing `init`-only properties on `this`
        // is allowed. Construct the nested instance via its own generated
        // (IConfigurationSection)-taking constructor for the same reason.
        writer.Write("this.");
        writer.Write(prop.Name);
        writer.Write(" = new ");
        writer.Write(nestedType);
        writer.Write('(');
        writer.Write(subsection);
        writer.WriteLine(");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    // ─────────────────────────────────────────────────────────────────────
    // DataAnnotations validation emission
    // ─────────────────────────────────────────────────────────────────────

    /// <summary>
    /// The email regex used by the BCL's <c>EmailAddressAttribute</c>.
    /// We inline the same pattern so the behaviour is familiar to users.
    /// </summary>
    private const string EmailRegexPattern = @"^[^@\s]+@[^@\s]+\.[^@\s]+$";

    /// <summary>
    /// Emits precompiled <c>private static readonly Regex</c> fields inside
    /// the Validator class for every <see cref="DataAnnotationKind.RegularExpression"/>
    /// and <see cref="DataAnnotationKind.EmailAddress"/> annotation.
    /// </summary>
    private static void WriteRegexFields(IndentedTextWriter writer, ConfigSectionModel model)
    {
        foreach (var prop in model.Properties)
        {
            foreach (var ann in prop.DataAnnotations)
            {
                if (ann.Kind == DataAnnotationKind.RegularExpression && ann.StringArg1 is not null)
                {
                    writer.Write("private static readonly global::System.Text.RegularExpressions.Regex _cb_Regex_");
                    writer.Write(prop.Name);
                    writer.Write(" = new global::System.Text.RegularExpressions.Regex(@\"");
                    // Verbatim string: only double-quotes need escaping (by doubling).
                    writer.Write(ann.StringArg1.Replace("\"", "\"\""));
                    writer.WriteLine("\", global::System.Text.RegularExpressions.RegexOptions.Compiled);");
                }
                else if (ann.Kind == DataAnnotationKind.EmailAddress)
                {
                    writer.Write("private static readonly global::System.Text.RegularExpressions.Regex _cb_Regex_Email_");
                    writer.Write(prop.Name);
                    writer.Write(" = new global::System.Text.RegularExpressions.Regex(@\"");
                    writer.Write(EmailRegexPattern.Replace("\"", "\"\""));
                    writer.WriteLine("\", global::System.Text.RegularExpressions.RegexOptions.Compiled);");
                }
            }
        }
    }

    /// <summary>
    /// Emits a single annotation validation check inside the <c>Validate</c>
    /// method body, dispatching on <see cref="DataAnnotationModel.Kind"/>.
    /// </summary>
    private static void WriteAnnotationCheck(
        IndentedTextWriter writer,
        ConfigSectionModel model,
        ConfigPropertyModel prop,
        DataAnnotationModel ann)
    {
        switch (ann.Kind)
        {
            case DataAnnotationKind.Required:
                // [Required] on a property that was already marked required by
                // nullability analysis is a no-op (CB0009 already warned). On a
                // property the existing pass didn't cover (e.g. a nullable string
                // with [Required]) we emit the check here.
                if (!prop.IsRequired)
                {
                    if (prop.IsString)
                    {
                        EmitStringNullOrWhitespace(writer, model, prop);
                    }
                    else if (prop.IsReferenceType)
                    {
                        EmitNullCheck(writer, model, prop);
                    }
                }
                break;

            case DataAnnotationKind.Range:
                EmitRangeCheck(writer, model, prop, ann);
                break;

            case DataAnnotationKind.StringLength:
                EmitStringLengthCheck(writer, model, prop, ann);
                break;

            case DataAnnotationKind.MinLength:
                EmitMinLengthCheck(writer, model, prop, ann);
                break;

            case DataAnnotationKind.MaxLength:
                EmitMaxLengthCheck(writer, model, prop, ann);
                break;

            case DataAnnotationKind.RegularExpression:
                EmitRegexCheck(writer, model, prop);
                break;

            case DataAnnotationKind.Url:
                EmitUrlCheck(writer, model, prop);
                break;

            case DataAnnotationKind.EmailAddress:
                EmitEmailCheck(writer, model, prop);
                break;

            case DataAnnotationKind.AllowedValues:
                EmitAllowedValuesCheck(writer, model, prop, ann);
                break;

            case DataAnnotationKind.DeniedValues:
                EmitDeniedValuesCheck(writer, model, prop, ann);
                break;
        }
    }

    /// <summary>Emits <c>if (string.IsNullOrWhiteSpace(options.X)) failures.Add(...);</c></summary>
    private static void EmitStringNullOrWhitespace(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop)
    {
        writer.Write("if (string.IsNullOrWhiteSpace(options.");
        writer.Write(prop.Name);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.WriteLine("] is required but was null, empty, or whitespace.\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Emits <c>if (options.X is null) failures.Add(...);</c></summary>
    private static void EmitNullCheck(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop)
    {
        writer.Write("if (options.");
        writer.Write(prop.Name);
        writer.WriteLine(" is null)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.WriteLine("] is required but was null.\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Emits <c>if (options.X &lt; min || options.X &gt; max) failures.Add(...);</c></summary>
    private static void EmitRangeCheck(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop, DataAnnotationModel ann)
    {
        if (!ann.NumericArg1.HasValue || !ann.NumericArg2.HasValue)
        {
            return;
        }

        var min = FormatNumericLiteral(ann.NumericArg1.Value, prop.ParseTypeKeyword);
        var max = FormatNumericLiteral(ann.NumericArg2.Value, prop.ParseTypeKeyword);

        writer.Write("if (options.");
        writer.Write(prop.Name);
        writer.Write(" < ");
        writer.Write(min);
        writer.Write(" || options.");
        writer.Write(prop.Name);
        writer.Write(" > ");
        writer.Write(max);
        writer.WriteLine(")");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.Write("] must be between ");
        writer.Write(min);
        writer.Write(" and ");
        writer.Write(max);
        writer.WriteLine(".\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Emits <c>if (options.X is not null &amp;&amp; (options.X.Length &lt; min || options.X.Length &gt; max))</c></summary>
    private static void EmitStringLengthCheck(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop, DataAnnotationModel ann)
    {
        // NumericArg1 = max length, NumericArg2 = min length (may be null).
        var maxLen = ann.NumericArg1.HasValue ? (int)ann.NumericArg1.Value : (int?)null;
        var minLen = ann.NumericArg2.HasValue ? (int)ann.NumericArg2.Value : 0;

        if (maxLen is null)
        {
            return;
        }

        writer.Write("if (options.");
        writer.Write(prop.Name);
        writer.Write(" is not null && (options.");
        writer.Write(prop.Name);
        writer.Write(".Length < ");
        writer.Write(minLen);
        writer.Write(" || options.");
        writer.Write(prop.Name);
        writer.Write(".Length > ");
        writer.Write(maxLen.Value);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.Write("] must have length between ");
        writer.Write(minLen);
        writer.Write(" and ");
        writer.Write(maxLen.Value);
        writer.WriteLine(".\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Emits <c>if (options.X is not null &amp;&amp; options.X.Length &lt; n)</c></summary>
    private static void EmitMinLengthCheck(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop, DataAnnotationModel ann)
    {
        if (!ann.NumericArg1.HasValue)
        {
            return;
        }

        var n = (int)ann.NumericArg1.Value;

        writer.Write("if (options.");
        writer.Write(prop.Name);
        writer.Write(" is not null && options.");
        writer.Write(prop.Name);
        writer.Write(".Length < ");
        writer.Write(n);
        writer.WriteLine(")");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.Write("] must have minimum length ");
        writer.Write(n);
        writer.WriteLine(".\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Emits <c>if (options.X is not null &amp;&amp; options.X.Length &gt; n)</c></summary>
    private static void EmitMaxLengthCheck(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop, DataAnnotationModel ann)
    {
        if (!ann.NumericArg1.HasValue)
        {
            return;
        }

        var n = (int)ann.NumericArg1.Value;

        writer.Write("if (options.");
        writer.Write(prop.Name);
        writer.Write(" is not null && options.");
        writer.Write(prop.Name);
        writer.Write(".Length > ");
        writer.Write(n);
        writer.WriteLine(")");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.Write("] must have maximum length ");
        writer.Write(n);
        writer.WriteLine(".\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Emits <c>if (options.X is not null &amp;&amp; !_cb_Regex_{X}.IsMatch(options.X))</c></summary>
    private static void EmitRegexCheck(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop)
    {
        writer.Write("if (options.");
        writer.Write(prop.Name);
        writer.Write(" is not null && !_cb_Regex_");
        writer.Write(prop.Name);
        writer.Write(".IsMatch(options.");
        writer.Write(prop.Name);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.WriteLine("] does not match the required pattern.\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Emits <c>if (options.X is not null &amp;&amp; !Uri.TryCreate(options.X, Absolute, out _))</c></summary>
    private static void EmitUrlCheck(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop)
    {
        writer.Write("if (options.");
        writer.Write(prop.Name);
        writer.Write(" is not null && !global::System.Uri.TryCreate(options.");
        writer.Write(prop.Name);
        writer.WriteLine(", global::System.UriKind.Absolute, out _))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.WriteLine("] is not a valid absolute URL.\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Emits <c>if (options.X is not null &amp;&amp; !_cb_Regex_Email_{X}.IsMatch(options.X))</c></summary>
    private static void EmitEmailCheck(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop)
    {
        writer.Write("if (options.");
        writer.Write(prop.Name);
        writer.Write(" is not null && !_cb_Regex_Email_");
        writer.Write(prop.Name);
        writer.Write(".IsMatch(options.");
        writer.Write(prop.Name);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.WriteLine("] is not a valid email address.\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Emits <c>if (!new[] { "A", "B" }.Contains(options.X))</c></summary>
    private static void EmitAllowedValuesCheck(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop, DataAnnotationModel ann)
    {
        if (ann.ValuesArg.Length == 0)
        {
            return;
        }

        writer.Write("if (");
        if (prop.IsString)
        {
            writer.Write("options.");
            writer.Write(prop.Name);
            writer.Write(" is not null && ");
        }

        writer.Write("!new[] { ");
        WriteValuesList(writer, ann.ValuesArg, prop.IsString);
        writer.Write(" }.Contains(options.");
        writer.Write(prop.Name);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.Write("] must be one of: ");
        writer.Write(string.Join(", ", ann.ValuesArg.AsArray()));
        writer.WriteLine(".\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Emits <c>if (new[] { "X" }.Contains(options.X))</c></summary>
    private static void EmitDeniedValuesCheck(IndentedTextWriter writer, ConfigSectionModel model, ConfigPropertyModel prop, DataAnnotationModel ann)
    {
        if (ann.ValuesArg.Length == 0)
        {
            return;
        }

        writer.Write("if (");
        if (prop.IsString)
        {
            writer.Write("options.");
            writer.Write(prop.Name);
            writer.Write(" is not null && ");
        }

        writer.Write("new[] { ");
        WriteValuesList(writer, ann.ValuesArg, prop.IsString);
        writer.Write(" }.Contains(options.");
        writer.Write(prop.Name);
        writer.WriteLine("))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.Write("failures.Add(\"[");
        writer.Write(Escape(model.SectionName));
        writer.Write(':');
        writer.Write(prop.Name);
        writer.Write("] must not be one of: ");
        writer.Write(string.Join(", ", ann.ValuesArg.AsArray()));
        writer.WriteLine(".\");");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>Writes a comma-separated list of values, quoting strings.</summary>
    private static void WriteValuesList(IndentedTextWriter writer, EquatableArray<string> values, bool quoteAsString)
    {
        for (int i = 0; i < values.Length; i++)
        {
            if (i > 0)
            {
                writer.Write(", ");
            }

            if (quoteAsString)
            {
                writer.Write('"');
                writer.Write(Escape(values[i]));
                writer.Write('"');
            }
            else
            {
                writer.Write(values[i]);
            }
        }
    }

    /// <summary>
    /// Formats a <c>double</c> value as a C# numeric literal appropriate for
    /// the given type keyword. For integer types we cast to <c>long</c> and
    /// emit a plain integer literal; for float/double/decimal we add the
    /// appropriate suffix.
    /// </summary>
    private static string FormatNumericLiteral(double value, string? parseTypeKeyword)
    {
        return parseTypeKeyword switch
        {
            "float" => value.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "f",
            "double" => value.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "d",
            "decimal" => value.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "m",
            _ => ((long)value).ToString(System.Globalization.CultureInfo.InvariantCulture),
        };
    }

    // ─────────────────────────────────────────────────────────────────────
    // Shared helpers
    // ─────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Builds a deterministic local-variable name for a property. We prefix
    /// with <c>_cb_</c> so the locals can never collide with another property
    /// or a user-defined identifier visible in the partial type's scope.
    /// </summary>
    private static string LocalName(string propertyName, string suffix) =>
        "_cb_" + propertyName + suffix;

    /// <summary>
    /// Escapes a string for safe inclusion inside a C# double-quoted literal.
    /// </summary>
    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
