// Copyright (c) ConfigBoundNET contributors. Licensed under the GPL-3 License.

using System.Collections.Generic;
using Xunit;

namespace ConfigBoundNET.Tests;

/// <summary>
/// End-to-end tests for the AOT-safe binder generated by
/// <see cref="ConfigBoundGenerator"/>. Each test compiles a synthetic
/// <c>[ConfigSection]</c> type, runs the generator, builds an in-memory
/// configuration, and asserts on the resulting <c>IOptions&lt;T&gt;.Value</c>.
/// </summary>
/// <remarks>
/// Together these prove the entire reflection-free pipeline works:
/// generator → ConfigBoundOptionsFactory replacement →
/// generated constructor → IConfiguration read.
/// They are intentionally one test per <see cref="BindingStrategy"/> branch
/// so a regression in any single strategy fails a single, named test.
/// </remarks>
public sealed class BindingTests
{
    [Fact]
    public void String_property_is_bound_from_section()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public string Conn { get; init; } = default!;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new Dictionary<string, string?> { ["Test:Conn"] = "hello world" });

        Assert.Equal("hello world", GetProp(bound, "Conn"));
    }

    [Fact]
    public void Missing_string_falls_back_to_field_initializer_default()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public string Region { get; init; } = "fallback";
            }
            """;

        // Provide an unrelated key so the section exists but Region is absent.
        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new Dictionary<string, string?> { ["Test:OtherKey"] = "noise" });

        Assert.Equal("fallback", GetProp(bound, "Region"));
    }

    [Fact]
    public void Integer_property_is_parsed_with_invariant_culture()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public int Port { get; init; }
                public long MaxBytes { get; init; }
                public byte Retries { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new Dictionary<string, string?>
            {
                ["Test:Port"] = "5432",
                ["Test:MaxBytes"] = "9999999999",
                ["Test:Retries"] = "7",
            });

        Assert.Equal(5432, GetProp(bound, "Port"));
        Assert.Equal(9999999999L, GetProp(bound, "MaxBytes"));
        Assert.Equal((byte)7, GetProp(bound, "Retries"));
    }

    [Fact]
    public void Floating_point_property_is_parsed_with_invariant_culture()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public double Ratio { get; init; }
                public decimal Price { get; init; }
            }
            """;

        // Use a dot as the decimal separator. Invariant culture means tests
        // pass the same way on every machine regardless of OS locale.
        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new Dictionary<string, string?>
            {
                ["Test:Ratio"] = "0.75",
                ["Test:Price"] = "19.95",
            });

        Assert.Equal(0.75, GetProp(bound, "Ratio"));
        Assert.Equal(19.95m, GetProp(bound, "Price"));
    }

    [Fact]
    public void Boolean_property_is_parsed()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public bool Enabled { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new Dictionary<string, string?> { ["Test:Enabled"] = "true" });

        Assert.Equal(true, GetProp(bound, "Enabled"));
    }

    [Fact]
    public void Guid_property_is_parsed()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public System.Guid TenantId { get; init; }
            }
            """;

        var expected = System.Guid.Parse("0c4f1b9a-7e3a-4b2d-9a8e-1c2d3e4f5a6b");

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new Dictionary<string, string?> { ["Test:TenantId"] = expected.ToString() });

        Assert.Equal(expected, GetProp(bound, "TenantId"));
    }

    [Fact]
    public void TimeSpan_property_is_parsed()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public System.TimeSpan Timeout { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new Dictionary<string, string?> { ["Test:Timeout"] = "00:01:30" });

        Assert.Equal(System.TimeSpan.FromSeconds(90), GetProp(bound, "Timeout"));
    }

    [Fact]
    public void DateTimeOffset_property_is_parsed()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public System.DateTimeOffset DeployedAt { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new Dictionary<string, string?> { ["Test:DeployedAt"] = "2026-04-10T08:30:00+00:00" });

        var actual = (System.DateTimeOffset)GetProp(bound, "DeployedAt")!;
        Assert.Equal(new System.DateTimeOffset(2026, 4, 10, 8, 30, 0, System.TimeSpan.Zero), actual);
    }

    [Fact]
    public void Uri_property_is_parsed_as_absolute()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public System.Uri Endpoint { get; init; } = default!;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new Dictionary<string, string?> { ["Test:Endpoint"] = "https://example.com/api" });

        Assert.Equal(new System.Uri("https://example.com/api"), GetProp(bound, "Endpoint"));
    }

    [Fact]
    public void Enum_property_is_parsed_case_insensitively()
    {
        // Declare the enum at namespace scope (not nested) and reference it.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            public enum LogLevel { Trace, Debug, Information, Warning }

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public LogLevel MinLevel { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            // Lower case in config; generator emits ignoreCase: true.
            new Dictionary<string, string?> { ["Test:MinLevel"] = "warning" });

        Assert.Equal("Warning", GetProp(bound, "MinLevel")!.ToString());
    }

    [Fact]
    public void Nested_config_section_is_recursively_bound()
    {
        // Both inner and outer types are [ConfigSection]-annotated. The outer
        // one's generated constructor recurses into the inner one's via the
        // generated (IConfigurationSection) ctor.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public string Conn { get; init; } = default!;
                public RetryPolicy Retry { get; init; } = default!;
            }

            [ConfigSection("__inner_unused__")]
            public partial record RetryPolicy
            {
                public int MaxAttempts { get; init; }
                public System.TimeSpan Backoff { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new Dictionary<string, string?>
            {
                ["Test:Conn"] = "Server=...",
                ["Test:Retry:MaxAttempts"] = "5",
                ["Test:Retry:Backoff"] = "00:00:02",
            });

        Assert.Equal("Server=...", GetProp(bound, "Conn"));

        var nested = GetProp(bound, "Retry")!;
        Assert.Equal(5, GetProp(nested, "MaxAttempts"));
        Assert.Equal(System.TimeSpan.FromSeconds(2), GetProp(nested, "Backoff"));
    }

    [Fact]
    public void Unsupported_property_type_raises_CB0010_warning_and_skips()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public string Conn { get; init; } = default!;

                // object is not in the supported binding set.
                public object Payload { get; init; } = default!;
            }
            """;

        var result = GeneratorHarness.Run(Source);

        Assert.Contains(
            result.Diagnostics,
            d => d.Id == "CB0010" && d.GetMessage().Contains("Payload"));
    }

    // ── Collection binding tests ─────────────────────────────────────────

    [Fact]
    public void String_array_is_bound_from_section()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public string[] Hosts { get; init; } = System.Array.Empty<string>();
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Test:Hosts:0"] = "host1.example.com",
                ["Test:Hosts:1"] = "host2.example.com",
            });

        var hosts = (System.Array)GetProp(bound, "Hosts")!;
        Assert.Equal(2, hosts.Length);
        Assert.Equal("host1.example.com", hosts.GetValue(0));
        Assert.Equal("host2.example.com", hosts.GetValue(1));
    }

    [Fact]
    public void Int_array_is_bound_from_section()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public int[] Ports { get; init; } = System.Array.Empty<int>();
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Test:Ports:0"] = "5432",
                ["Test:Ports:1"] = "5433",
                ["Test:Ports:2"] = "5434",
            });

        var ports = (System.Array)GetProp(bound, "Ports")!;
        Assert.Equal(3, ports.Length);
        Assert.Equal(5432, ports.GetValue(0));
    }

    [Fact]
    public void String_dictionary_is_bound_from_section()
    {
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public Dictionary<string, string> Headers { get; init; } = new();
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Test:Headers:X-Api-Key"] = "secret",
                ["Test:Headers:Content-Type"] = "application/json",
            });

        // Dictionary is bound — access via reflection.
        var headers = GetProp(bound, "Headers")!;
        var count = (int)headers.GetType().GetProperty("Count")!.GetValue(headers)!;
        Assert.Equal(2, count);
    }

    [Fact]
    public void Absent_collection_preserves_default_value()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public string[] Tags { get; init; } = new[] { "default" };
            }
            """;

        // No Test:Tags keys in config → default should be preserved.
        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Test:OtherKey"] = "noise",
            });

        var tags = (System.Array)GetProp(bound, "Tags")!;
        Assert.Single(tags);
        Assert.Equal("default", tags.GetValue(0));
    }

    // ── Nested config validation tests ─────────────────────────────────

    [Fact]
    public void Nested_config_validation_recurses_into_inner_type()
    {
        // RetryConfig has [Range(1, 20)] on MaxAttempts. Setting it to 99
        // should fail validation even though the parent DbConfig itself
        // is well-formed. This proves the parent Validator calls the nested
        // Validator recursively.
        const string Source = """
            using ConfigBoundNET;
            using System.ComponentModel.DataAnnotations;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public string Conn { get; init; } = default!;
                public RetryConfig Retry { get; init; } = default!;
            }

            [ConfigSection("__inner__")]
            public partial record RetryConfig
            {
                [Range(1, 20)]
                public int MaxAttempts { get; init; }
            }
            """;

        var ex = Assert.ThrowsAny<System.Exception>(() =>
            GeneratorHarness.CompileAndBind(
                Source,
                "TestConfig",
                new System.Collections.Generic.Dictionary<string, string?>
                {
                    ["Test:Conn"] = "hello",
                    ["Test:Retry:MaxAttempts"] = "99",
                }));

        Assert.Contains("must be between 1 and 20", ex.InnerException?.Message ?? ex.Message);
    }

    [Fact]
    public void NestedConfig_list_binds_from_in_memory_configuration()
    {
        // List<EndpointConfig> where EndpointConfig is itself [ConfigSection]-
        // annotated. Each child section under "Api:Endpoints:{i}" is passed to
        // EndpointConfig's generated (IConfigurationSection) constructor.
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public List<EndpointConfig> Endpoints { get; init; } = new();
            }

            [ConfigSection("__endpoint__")]
            public partial record EndpointConfig
            {
                public string Url { get; init; } = default!;
                public System.TimeSpan Timeout { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "ApiConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Api:Endpoints:0:Url"] = "https://a.example/",
                ["Api:Endpoints:0:Timeout"] = "00:00:10",
                ["Api:Endpoints:1:Url"] = "https://b.example/",
                ["Api:Endpoints:1:Timeout"] = "00:00:20",
            });

        var endpoints = GetProp(bound, "Endpoints")!;
        var count = (int)endpoints.GetType().GetProperty("Count")!.GetValue(endpoints)!;
        Assert.Equal(2, count);

        // Enumerate to verify element values.
        var list = (System.Collections.IEnumerable)endpoints;
        var items = new System.Collections.Generic.List<object>();
        foreach (var item in list) items.Add(item);

        Assert.Equal("https://a.example/", GetProp(items[0], "Url"));
        Assert.Equal(System.TimeSpan.FromSeconds(10), GetProp(items[0], "Timeout"));
        Assert.Equal("https://b.example/", GetProp(items[1], "Url"));
        Assert.Equal(System.TimeSpan.FromSeconds(20), GetProp(items[1], "Timeout"));
    }

    [Fact]
    public void NestedConfig_array_binds_from_in_memory_configuration()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public EndpointConfig[] Endpoints { get; init; } = System.Array.Empty<EndpointConfig>();
            }

            [ConfigSection("__endpoint__")]
            public partial record EndpointConfig
            {
                public string Url { get; init; } = default!;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "ApiConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Api:Endpoints:0:Url"] = "https://a.example/",
                ["Api:Endpoints:1:Url"] = "https://b.example/",
            });

        var endpoints = (System.Array)GetProp(bound, "Endpoints")!;
        Assert.Equal(2, endpoints.Length);
        Assert.Equal("https://a.example/", GetProp(endpoints.GetValue(0)!, "Url"));
        Assert.Equal("https://b.example/", GetProp(endpoints.GetValue(1)!, "Url"));
    }

    [Fact]
    public void NestedConfig_readonly_list_binds_from_in_memory_configuration()
    {
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public IReadOnlyList<EndpointConfig> Endpoints { get; init; } = new List<EndpointConfig>();
            }

            [ConfigSection("__endpoint__")]
            public partial record EndpointConfig
            {
                public string Url { get; init; } = default!;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "ApiConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Api:Endpoints:0:Url"] = "https://a.example/",
            });

        var endpoints = GetProp(bound, "Endpoints")!;
        var count = (int)endpoints.GetType().GetProperty("Count")!.GetValue(endpoints)!;
        Assert.Equal(1, count);
    }

    [Fact]
    public void NestedConfig_list_absent_section_preserves_default()
    {
        // No "Api:Endpoints" children → generator must leave the user-declared
        // default (an empty List<T> from the field initializer) untouched.
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public List<EndpointConfig> Endpoints { get; init; } = new();
            }

            [ConfigSection("__endpoint__")]
            public partial record EndpointConfig
            {
                public string Url { get; init; } = default!;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "ApiConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Api:Other"] = "noise",
            });

        var endpoints = GetProp(bound, "Endpoints")!;
        var count = (int)endpoints.GetType().GetProperty("Count")!.GetValue(endpoints)!;
        Assert.Equal(0, count);
    }

    [Fact]
    public void NestedConfig_list_failure_message_includes_full_path()
    {
        // An out-of-range value on element 1 must produce a failure keyed by
        // "[Api:Endpoints:1:Port]", NOT "[__endpoint__:Port]". This proves the
        // path-aware Validator overload threads the full path through nested
        // collection recursion.
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;
            using System.ComponentModel.DataAnnotations;

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public List<EndpointConfig> Endpoints { get; init; } = new();
            }

            [ConfigSection("__endpoint__")]
            public partial record EndpointConfig
            {
                [Range(1, 65535)]
                public int Port { get; init; }
            }
            """;

        var ex = Assert.ThrowsAny<System.Exception>(() =>
            GeneratorHarness.CompileAndBind(
                Source,
                "ApiConfig",
                new System.Collections.Generic.Dictionary<string, string?>
                {
                    ["Api:Endpoints:0:Port"] = "8080",
                    ["Api:Endpoints:1:Port"] = "999999",
                }));

        var message = ex.InnerException?.Message ?? ex.Message;
        Assert.Contains("[Api:Endpoints:1:Port]", message);
        Assert.DoesNotContain("__endpoint__", message);
    }

    [Fact]
    public void Single_nested_failure_message_includes_parent_path()
    {
        // Single-nested recursion: the parent's Validate passes path + ":Retry"
        // down, so the failure reads "[Db:Retry:MaxAttempts]" instead of
        // "[__inner__:MaxAttempts]".
        const string Source = """
            using ConfigBoundNET;
            using System.ComponentModel.DataAnnotations;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                public string Conn { get; init; } = default!;
                public RetryConfig Retry { get; init; } = default!;
            }

            [ConfigSection("__inner__")]
            public partial record RetryConfig
            {
                [Range(1, 20)]
                public int MaxAttempts { get; init; }
            }
            """;

        var ex = Assert.ThrowsAny<System.Exception>(() =>
            GeneratorHarness.CompileAndBind(
                Source,
                "DbConfig",
                new System.Collections.Generic.Dictionary<string, string?>
                {
                    ["Db:Conn"] = "hello",
                    ["Db:Retry:MaxAttempts"] = "99",
                }));

        var message = ex.InnerException?.Message ?? ex.Message;
        Assert.Contains("[Db:Retry:MaxAttempts]", message);
        Assert.DoesNotContain("__inner__", message);
    }

    [Fact]
    public void NestedConfig_list_with_nullable_element_round_trips()
    {
        // List<EndpointConfig?> must bind and validate identically to
        // List<EndpointConfig> — the binder never produces null elements,
        // and the generated container matches the user's declaration so the
        // assignment type-checks under strict nullable.
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;

            #nullable enable

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public List<EndpointConfig?> Endpoints { get; init; } = new();
            }

            [ConfigSection("__endpoint__")]
            public partial record EndpointConfig
            {
                public string Url { get; init; } = default!;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "ApiConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Api:Endpoints:0:Url"] = "https://a.example/",
                ["Api:Endpoints:1:Url"] = "https://b.example/",
            });

        var endpoints = GetProp(bound, "Endpoints")!;
        var count = (int)endpoints.GetType().GetProperty("Count")!.GetValue(endpoints)!;
        Assert.Equal(2, count);

        var list = (System.Collections.IEnumerable)endpoints;
        foreach (var item in list)
        {
            Assert.NotNull(item);
        }
    }

    [Fact]
    public void Path_aware_ValidateCustom_receives_full_path()
    {
        // The path-aware ValidateCustom overload must receive "Db:Retry" when
        // RetryConfig is reached through the nested-config recursion, not its
        // own SectionName "__inner__".
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                public string Conn { get; init; } = default!;
                public RetryConfig Retry { get; init; } = default!;
            }

            [ConfigSection("__inner__")]
            public partial record RetryConfig
            {
                public int MaxAttempts { get; init; }

                partial void ValidateCustom(List<string> failures, string path)
                {
                    // Unconditionally add a failure that quotes the path, so
                    // the test can assert on what we received.
                    failures.Add("[" + path + "] custom-hook saw path = '" + path + "'.");
                }
            }
            """;

        var ex = Assert.ThrowsAny<System.Exception>(() =>
            GeneratorHarness.CompileAndBind(
                Source,
                "DbConfig",
                new System.Collections.Generic.Dictionary<string, string?>
                {
                    ["Db:Conn"] = "hello",
                    ["Db:Retry:MaxAttempts"] = "3",
                }));

        var message = ex.InnerException?.Message ?? ex.Message;
        Assert.Contains("custom-hook saw path = 'Db:Retry'", message);
    }

    [Fact]
    public void NestedConfig_dictionary_binds_from_in_memory_configuration()
    {
        // Dictionary<string, TenantConfig> where TenantConfig is itself
        // [ConfigSection]-annotated. Each child section under "Api:Tenants:{key}"
        // becomes dict[key] = new TenantConfig(child).
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public Dictionary<string, TenantConfig> Tenants { get; init; } = new();
            }

            [ConfigSection("__tenant__")]
            public partial record TenantConfig
            {
                public string BaseUrl { get; init; } = default!;
                public System.TimeSpan Timeout { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "ApiConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Api:Tenants:acme:BaseUrl"] = "https://acme.example/",
                ["Api:Tenants:acme:Timeout"] = "00:00:30",
                ["Api:Tenants:globex:BaseUrl"] = "https://globex.example/",
                ["Api:Tenants:globex:Timeout"] = "00:00:10",
            });

        var tenants = GetProp(bound, "Tenants")!;
        var count = (int)tenants.GetType().GetProperty("Count")!.GetValue(tenants)!;
        Assert.Equal(2, count);

        // Access entries via the indexer to confirm keyed round-trip.
        var indexer = tenants.GetType().GetProperty("Item")!;
        var acme = indexer.GetValue(tenants, new object[] { "acme" })!;
        var globex = indexer.GetValue(tenants, new object[] { "globex" })!;

        Assert.Equal("https://acme.example/", GetProp(acme, "BaseUrl"));
        Assert.Equal(System.TimeSpan.FromSeconds(30), GetProp(acme, "Timeout"));
        Assert.Equal("https://globex.example/", GetProp(globex, "BaseUrl"));
        Assert.Equal(System.TimeSpan.FromSeconds(10), GetProp(globex, "Timeout"));
    }

    [Fact]
    public void NestedConfig_dictionary_absent_section_preserves_default()
    {
        // No "Api:Tenants" keys → the generator must leave the user's
        // new() default (an empty dictionary) untouched.
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public Dictionary<string, TenantConfig> Tenants { get; init; } = new();
            }

            [ConfigSection("__tenant__")]
            public partial record TenantConfig
            {
                public string BaseUrl { get; init; } = default!;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "ApiConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Api:OtherKey"] = "noise",
            });

        var tenants = GetProp(bound, "Tenants")!;
        var count = (int)tenants.GetType().GetProperty("Count")!.GetValue(tenants)!;
        Assert.Equal(0, count);
    }

    [Fact]
    public void NestedConfig_dictionary_failure_message_includes_key_in_path()
    {
        // Inner [Range] failure on the "acme" entry must produce a failure
        // keyed by "[Api:Tenants:acme:Port]", NOT "[__tenant__:Port]".
        // This proves the path-aware Validator threads the config key
        // through dictionary-of-nested recursion.
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;
            using System.ComponentModel.DataAnnotations;

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public Dictionary<string, TenantConfig> Tenants { get; init; } = new();
            }

            [ConfigSection("__tenant__")]
            public partial record TenantConfig
            {
                [Range(1, 65535)]
                public int Port { get; init; }
            }
            """;

        var ex = Assert.ThrowsAny<System.Exception>(() =>
            GeneratorHarness.CompileAndBind(
                Source,
                "ApiConfig",
                new System.Collections.Generic.Dictionary<string, string?>
                {
                    ["Api:Tenants:acme:Port"] = "999999",
                    ["Api:Tenants:globex:Port"] = "8080",
                }));

        var message = ex.InnerException?.Message ?? ex.Message;
        Assert.Contains("[Api:Tenants:acme:Port]", message);
        Assert.DoesNotContain("__tenant__", message);
    }

    [Fact]
    public void NestedConfig_dictionary_with_nullable_value_round_trips()
    {
        // Dictionary<string, TenantConfig?> must bind and validate identically
        // to Dictionary<string, TenantConfig> — the binder never produces null
        // values, and the container type matches the user's declaration so
        // the assignment type-checks under strict nullable.
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;

            #nullable enable

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public Dictionary<string, TenantConfig?> Tenants { get; init; } = new();
            }

            [ConfigSection("__tenant__")]
            public partial record TenantConfig
            {
                public string BaseUrl { get; init; } = default!;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "ApiConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Api:Tenants:acme:BaseUrl"] = "https://acme.example/",
            });

        var tenants = GetProp(bound, "Tenants")!;
        var count = (int)tenants.GetType().GetProperty("Count")!.GetValue(tenants)!;
        Assert.Equal(1, count);
    }

    [Fact]
    public void NestedConfig_list_inner_validation_failures_surface()
    {
        // EndpointConfig has [Range(1, 65535)] on Port. An out-of-range value
        // on any element must fail the parent's validation.
        const string Source = """
            using ConfigBoundNET;
            using System.Collections.Generic;
            using System.ComponentModel.DataAnnotations;

            namespace MyApp;

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public List<EndpointConfig> Endpoints { get; init; } = new();
            }

            [ConfigSection("__endpoint__")]
            public partial record EndpointConfig
            {
                [Range(1, 65535)]
                public int Port { get; init; }
            }
            """;

        var ex = Assert.ThrowsAny<System.Exception>(() =>
            GeneratorHarness.CompileAndBind(
                Source,
                "ApiConfig",
                new System.Collections.Generic.Dictionary<string, string?>
                {
                    ["Api:Endpoints:0:Port"] = "8080",
                    ["Api:Endpoints:1:Port"] = "999999",
                }));

        Assert.Contains("must be between 1 and 65535", ex.InnerException?.Message ?? ex.Message);
    }

    [Fact]
    public void Nested_config_validation_passes_when_inner_is_valid()
    {
        const string Source = """
            using ConfigBoundNET;
            using System.ComponentModel.DataAnnotations;

            namespace MyApp;

            [ConfigSection("Test")]
            public partial record TestConfig
            {
                public string Conn { get; init; } = default!;
                public RetryConfig Retry { get; init; } = default!;
            }

            [ConfigSection("__inner__")]
            public partial record RetryConfig
            {
                [Range(1, 20)]
                public int MaxAttempts { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "TestConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Test:Conn"] = "hello",
                ["Test:Retry:MaxAttempts"] = "5",
            });

        var nested = GetProp(bound, "Retry")!;
        Assert.Equal(5, GetProp(nested, "MaxAttempts"));
    }

    // ── Allocation contract ─────────────────────────────────────────────

    [Fact]
    public void Validator_success_path_allocates_no_failures_list()
    {
        // The generated Validator starts failures as null and only allocates
        // the List<string> when a failure actually fires. On the success path
        // (every check passes, no ValidateCustom hook implemented), a single
        // Validate call must allocate nothing beyond tiny overhead from the
        // call frame itself — definitely no List<string>, no array, and no
        // boxed enumerator. This test guards that contract.
        const string Source = """
            using ConfigBoundNET;
            using System.ComponentModel.DataAnnotations;

            namespace MyApp;

            [ConfigSection("Alloc")]
            public partial record AllocConfig
            {
                public string Name { get; init; } = default!;

                [Range(1, 65535)]
                public int Port { get; init; } = 8080;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "AllocConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Alloc:Name"] = "ok",
                ["Alloc:Port"] = "8080",
            });

        // Locate the generated Validator and the 3-arg Validate overload
        // directly so we measure just that call, not DI/IOptions plumbing.
        var validatorType = bound.GetType().GetNestedType("Validator")!;
        var validator = System.Activator.CreateInstance(validatorType)!;
        var validate = validatorType.GetMethod(
            "Validate",
            new[] { typeof(string), typeof(string), bound.GetType() })!;

        // Warm up: first call may allocate some JIT/tiered-comp state
        // unrelated to our List<string> concern.
        for (int i = 0; i < 50; i++)
        {
            validate.Invoke(validator, new object?[] { null, "Alloc", bound });
        }

        // Measure one call's allocations. GC.GetAllocatedBytesForCurrentThread
        // reports cumulative thread-local allocation; the delta is our signal.
        var before = System.GC.GetAllocatedBytesForCurrentThread();
        validate.Invoke(validator, new object?[] { null, "Alloc", bound });
        var after = System.GC.GetAllocatedBytesForCurrentThread();

        var delta = after - before;

        // Invoking via MethodInfo.Invoke itself allocates a params object[]
        // and an object for the boxed return value, so we expect some small
        // overhead. Before this optimisation the delta was ~200+ B (the list
        // dominated). After, it's comfortably under 150 B. Pin at < 200 B to
        // absorb future reflection-overhead drift without losing the signal.
        Assert.True(
            delta < 200,
            $"Validator.Validate on success path allocated {delta} B — expected < 200 B. " +
            "A regression here usually means the lazy failures-list allocation " +
            "(FailuresAccessor in SourceEmitter) has been bypassed or reverted.");
    }

    // ── [Sensitive] redaction ───────────────────────────────────────────

    [Fact]
    public void Sensitive_attribute_redacts_reference_type_in_ToString()
    {
        // A [Sensitive] string property must print as "***" in ToString()
        // so it doesn't leak through `logger.LogInformation("{Config}", c)`
        // or direct ToString() calls.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                [Sensitive]
                public string Conn { get; init; } = default!;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "DbConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Conn"] = "Server=secret-host;User=alice;Password=hunter2",
            });

        var s = bound.ToString()!;
        Assert.Contains("Conn = ***", s);
        Assert.DoesNotContain("hunter2", s);
        Assert.DoesNotContain("secret-host", s);
    }

    [Fact]
    public void Sensitive_attribute_prints_null_for_null_reference()
    {
        // Null-valued sensitive properties render as "null" so missing
        // config is distinguishable from set-but-redacted at debug time.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                [Sensitive]
                public string? Conn { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "DbConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Other"] = "noise",
            });

        var s = bound.ToString()!;
        Assert.Contains("Conn = null", s);
        Assert.DoesNotContain("***", s);
    }

    [Fact]
    public void Sensitive_attribute_redacts_value_type()
    {
        // Value-type sensitives always render as "***" — there's no null
        // case to distinguish, so we don't bother with the ternary.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Auth")]
            public partial record AuthConfig
            {
                [Sensitive]
                public System.Guid Token { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "AuthConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Auth:Token"] = "0c4f1b9a-7e3a-4b2d-9a8e-1c2d3e4f5a6b",
            });

        var s = bound.ToString()!;
        Assert.Contains("Token = ***", s);
        Assert.DoesNotContain("0c4f1b9a", s);
    }

    [Fact]
    public void Sensitive_attribute_leaves_non_sensitive_properties_unchanged()
    {
        // Only properties marked [Sensitive] are redacted. Everything else
        // renders with its real value, so logs keep their diagnostic value.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                [Sensitive]
                public string Conn { get; init; } = default!;

                public int Port { get; init; } = 5432;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "DbConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Conn"] = "Server=secret",
                ["Db:Port"] = "8080",
            });

        var s = bound.ToString()!;
        Assert.Contains("Conn = ***", s);
        Assert.Contains("Port = 8080", s);
        Assert.DoesNotContain("Server=secret", s);
    }

    // ── [Sensitive] structured-logging redaction via IReadOnlyDictionary ──

    [Fact]
    public void Sensitive_config_implements_ReadOnlyDictionary_with_redacted_values()
    {
        // TryGetValue is the core contract: Serilog, System.Text.Json,
        // MEL's JsonConsoleFormatter and friends all call into it (or
        // enumerate) to retrieve structured values. Sensitive properties
        // must come back redacted; non-sensitive ones pass through.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                [Sensitive]
                public string Conn { get; init; } = default!;
                public int Port { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "DbConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Conn"] = "Server=secret-host;Password=hunter2",
                ["Db:Port"] = "5432",
            });

        var dict = (System.Collections.Generic.IReadOnlyDictionary<string, object?>)bound;

        Assert.True(dict.TryGetValue("Conn", out var conn));
        Assert.Equal("***", conn);

        Assert.True(dict.TryGetValue("Port", out var port));
        Assert.Equal(5432, port);

        Assert.False(dict.TryGetValue("DoesNotExist", out var missing));
        Assert.Null(missing);
    }

    [Fact]
    public void Sensitive_config_Keys_returns_all_property_names()
    {
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                [Sensitive]
                public string Conn { get; init; } = default!;
                public int Port { get; init; }
                public string Host { get; init; } = default!;
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "DbConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Conn"] = "x",
                ["Db:Host"] = "localhost",
            });

        var dict = (System.Collections.Generic.IReadOnlyDictionary<string, object?>)bound;

        var expected = new[] { "Conn", "Port", "Host" };
        Assert.Equal(expected, dict.Keys);
    }

    [Fact]
    public void Sensitive_config_Count_matches_property_count()
    {
        // Count is hardcoded at generate time; make sure we're counting
        // every public property, not just the sensitive ones.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                [Sensitive]
                public string Conn { get; init; } = default!;
                public int Port { get; init; }
                public string Host { get; init; } = default!;
                public System.TimeSpan Timeout { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "DbConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Conn"] = "x",
                ["Db:Host"] = "localhost",
            });

        var dict = (System.Collections.Generic.IReadOnlyDictionary<string, object?>)bound;
        Assert.Equal(4, dict.Count);
    }

    [Fact]
    public void Sensitive_config_enumerates_as_KVPs_with_redaction()
    {
        // foreach over the interface cast — the path Serilog's
        // default destructurer actually takes when it sees
        // IEnumerable<KeyValuePair<string, object?>>.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                [Sensitive]
                public string Conn { get; init; } = default!;
                public int Port { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "DbConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Conn"] = "Server=secret-host",
                ["Db:Port"] = "5432",
            });

        var dict = (System.Collections.Generic.IReadOnlyDictionary<string, object?>)bound;
        var pairs = new System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object?>>();
        foreach (var kvp in dict)
        {
            pairs.Add(kvp);
        }

        Assert.Equal(2, pairs.Count);
        Assert.Equal("Conn", pairs[0].Key);
        Assert.Equal("***", pairs[0].Value);
        Assert.Equal("Port", pairs[1].Key);
        Assert.Equal(5432, pairs[1].Value);
    }

    [Fact]
    public void Sensitive_config_json_serialization_redacts_through_dictionary_path()
    {
        // The end-to-end "transparent across frameworks" proof:
        // JsonSerializer.Serialize(config) with NO custom converter, NO
        // source-gen context, and NO ToString involvement. STJ picks its
        // ReadOnlyDictionaryConverter for our type and writes each property
        // as a JSON key with the (possibly redacted) value.
        //
        // This is what MEL's JsonConsoleFormatter and most OpenTelemetry
        // JSON log exporters do under the hood when they serialize a
        // structured-log argument.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                [Sensitive]
                public string Conn { get; init; } = default!;
                public int Port { get; init; }
            }
            """;

        var bound = GeneratorHarness.CompileAndBind(
            Source,
            "DbConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Conn"] = "Server=secret-host;Password=hunter2",
                ["Db:Port"] = "5432",
            });

        // Cast to object so STJ picks the runtime-type converter — matches
        // how MEL and OTel serialize log-scope arguments (they have a
        // System.Object-typed slot, not a strongly-typed one).
        var json = System.Text.Json.JsonSerializer.Serialize((object)bound);

        Assert.Contains("\"Conn\":\"***\"", json);
        Assert.Contains("\"Port\":5432", json);
        Assert.DoesNotContain("hunter2", json);
        Assert.DoesNotContain("secret-host", json);
    }

    // ── Aggregate registration tests ─────────────────────────────────────

    [Fact]
    public void AddConfigBoundSections_registers_every_present_section()
    {
        // Two [ConfigSection] types, both sections present in config. The
        // aggregate extension must register both and bind both correctly.
        const string Source = """
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                public string Conn { get; init; } = default!;
            }

            [ConfigSection("Api")]
            public partial record ApiConfig
            {
                public string BaseUrl { get; init; } = default!;
            }
            """;

        var dbBound = GeneratorHarness.CompileAndBindViaAggregate(
            Source,
            "DbConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Conn"] = "Server=localhost",
                ["Api:BaseUrl"] = "https://api.example/",
            });

        Assert.Equal("Server=localhost", GetProp(dbBound, "Conn"));

        // Second resolve against the aggregate path too, to prove both types
        // were actually registered.
        var apiBound = GeneratorHarness.CompileAndBindViaAggregate(
            Source,
            "ApiConfig",
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Conn"] = "Server=localhost",
                ["Api:BaseUrl"] = "https://api.example/",
            });

        Assert.Equal("https://api.example/", GetProp(apiBound, "BaseUrl"));
    }

    [Fact]
    public void AddConfigBoundSections_skips_nested_referenced_type_whose_section_is_absent()
    {
        // The gate now fires only for types the aggregate classifies as
        // nested — either via a nested-property reference from another
        // [ConfigSection] (the inference path exercised here) or via an
        // explicit IsNestedOnly=true flag on the attribute. This fixture
        // embeds List<TenantConfig> inside DbConfig, so inference flips
        // TenantConfig's IsReferencedAsNested to true and the aggregate
        // wraps its AddTenantConfig call in .Exists(). With only the "Db"
        // section present, the "__tenant__" section is absent and the
        // TenantConfig validator is never registered — no spurious
        // "[__tenant__:Url] is required" at startup.
        const string Source = """
            using System.Collections.Generic;
            using ConfigBoundNET;

            namespace MyApp;

            [ConfigSection("__tenant__")]
            public partial record TenantConfig
            {
                public string Url { get; init; } = default!;
            }

            [ConfigSection("Db")]
            public partial record DbConfig
            {
                public string Conn { get; init; } = default!;
                public List<TenantConfig> Tenants { get; init; } = new();
            }
            """;

        // Run the aggregate, inspect the service collection afterwards.
        var (assembly, services) = GeneratorHarness.CompileAndAggregate(
            Source,
            new System.Collections.Generic.Dictionary<string, string?>
            {
                ["Db:Conn"] = "Server=localhost",
            });

        var dbConfigType = assembly.GetTypes().Single(t => t.Name == "DbConfig");
        var tenantConfigType = assembly.GetTypes().Single(t => t.Name == "TenantConfig");

        var dbValidatorServiceType = typeof(Microsoft.Extensions.Options.IValidateOptions<>)
            .MakeGenericType(dbConfigType);
        var tenantValidatorServiceType = typeof(Microsoft.Extensions.Options.IValidateOptions<>)
            .MakeGenericType(tenantConfigType);

        // DbConfig's section exists → its validator is registered.
        Assert.Contains(services, sd => sd.ServiceType == dbValidatorServiceType);

        // TenantConfig is inferred-nested and its section is absent →
        // the aggregate's .Exists() gate skipped it, so its validator
        // was never registered at the root.
        Assert.DoesNotContain(services, sd => sd.ServiceType == tenantValidatorServiceType);
    }

    /// <summary>
    /// Reflection helper that mirrors what a real consumer would write
    /// statically as <c>options.Conn</c>. Used here only because the test type
    /// is built dynamically inside the generator harness.
    /// </summary>
    private static object? GetProp(object instance, string name)
        => instance.GetType().GetProperty(name)!.GetValue(instance);
}
